### ISSUE TITLE
Detection from WebCam Capture using EmguCV

### ISSUE THREAD

**Issue by vankyy26** [AlturosDestinations/Alturos.Yolo#1]
Hello! Nice wrapper! I tried it over some existing images and worked well but I have a problem using it with capture from my laptop camera. EmguCV is processing the bitmaps well and detects my face without issues but ProcessImage always returns null. The wrapper is initializing properly. Marshal.GetLastWin32Error() returns error code 203. I'm converting the Capture frames from their bitmaps to byte arrays using LockBits. Will put some code samples below so you can test. I'm using the latest Emgu from NuGet version 3.1.0.1.

```
using (var imageFrame = this.capture.QueryFrame().ToImage<Bgr, Byte>())
            {
                if (imageFrame != null)
                {
                    CoreRectangleCandidate[] yoloObjects = this.yoloWrapper.ProcessImage(BitmapToByteArray(imageFrame.Bitmap));

                    int errorMessage = Marshal.GetLastWin32Error();

                    if (yoloObjects != null)
                    {
                        foreach (CoreRectangleCandidate rect in yoloObjects.Where(wr => wr.objectType == "person"))
                        {
                            imageFrame.Draw(new Rectangle(rect.rectangle.topLeftCorner.x, rect.rectangle.topLeftCorner.y, rect.rectangle.width, rect.rectangle.height),
                                new Bgr(Color.Wheat), 3);
                        }
                    }
}
}

public static byte[] BitmapToByteArray(Bitmap bitmap)
        {

            BitmapData bmpdata = null;

            try
            {
                bmpdata = bitmap.LockBits(new Rectangle(0, 0, bitmap.Width, bitmap.Height), ImageLockMode.ReadOnly, bitmap.PixelFormat);
                int numbytes = bmpdata.Stride * bitmap.Height;
                byte[] bytedata = new byte[numbytes];
                IntPtr ptr = bmpdata.Scan0;

                Marshal.Copy(ptr, bytedata, 0, numbytes);

                return bytedata;
            }
            finally
            {
                if (bmpdata != null)
                    bitmap.UnlockBits(bmpdata);
            }

        }
```

**Comment by vankyy26** [comment]
Yea, that did it, this time worked. Seems to be detecting well but the fps is super low. I'm running it on GPU- Nvidia GeForce GTX 1050, CPU - i7 7700HQ 2.8GHz. My camera is capturing video with 720p resolution. Definitely the slowdown is caused by Yolo, because without it EmguCV has a decent fps (between 20 and 30 frames). I will put some Stopwatchs and update my comment..

**Comment by tinohager** [comment]
The problem is this project support currently only cpu detection. Your GPU is not used. We are planning the support. If you need more power you can use this multi core cpu version.
[yolo.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/2111031/yolo.zip)

**Comment by vankyy26** [comment]
I see, yea that's what i thought. Thanks about this update, the fps is drastically increased and of course the CPU usage, too. I'll be waiting for the Cuda update, if I can help with something just let me know. Yolo is new for me yet but I'm experienced in .NET and C++ so I could help with something if needed. If you needed tester I can join in that, too. :)

**Comment by tinohager** [comment]
Yes i can need your help, i am currently trying this library https://github.com/AlexeyAB/darknet on the end is a documentation to compile the project as a dll, also gpu support is available. I found this [bridge class](https://github.com/rodrigojbp/YoloCSharp/blob/master/YoloNOGPUCSharpClient/YoloBridge.cs) but its not works...  ``System.EntryPointNotFoundException``

I have compiled with CUDA 9.2 support
[yolo_cpp_dll.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/2113212/yolo_cpp_dll.zip)

**Comment by tinohager** [comment]
I have a open issue on the project of AlexeyAB with my changes https://github.com/AlexeyAB/darknet/issues/1072

**Comment by vankyy26** [comment]
Can you send the other binaries (opencv etc.) because it doesn't seems to work with the binaries which I have currently. I don't have darknet configured to build..

**Comment by tinohager** [comment]
The files are very big

you need opencv 3.4.0 https://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.4.0/opencv-3.4.0-vc14_vc15.exe/download
And Cuda 9.2 https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork

**Comment by tinohager** [comment]
Alturos.Yolo.dll
Alturos.Yolo.pdb
Alturos.Yolo.TestUI.exe
Alturos.Yolo.TestUI.exe.config
Alturos.Yolo.TestUI.pdb
cudnn64_7.dll
opencv_ffmpeg340_64.dll
opencv_world340.dll
pthreadGC2.dll
pthreadVC2.dll
voc.names
yolo.dll
yolov2-tiny-voc.cfg
yolov2-tiny-voc.weights
yolo_cpp_dll.dll

**Comment by tt20496** [comment]
Hey vankyy26 can you give me file .sln ? i'm Engineering mechanics so it's important for me to finish graduation thesis.Thank you.
sorry for my bad english

**Comment by AlievR** [comment]
@vankyy26 , can you please help me with detection from WebCam Capture using EmguCV.

**Comment by tt20496** [comment]
> @vankyy26 , can you please help me with detection from WebCam Capture using EmguCV.

Hello AlievR, Give me your email? I'll send to you Tutorial

**Comment by tinohager** [comment]
@tt20496 It is possible to share it here? For other users? 😄

**Comment by AlievR** [comment]
@tt20496, maill: raslkrut5@mail.ru
Thanks for the help.

**Comment by tt20496** [comment]
> @tt20496, maill: [raslkrut5@mail.ru](mailto:raslkrut5@mail.ru)
> Thanks for the help.


i'm newbie so I follow this video to finish project:
Capture EmguCV: https://www.youtube.com/watch?v=MXjM4iN261s
Yolo Detection: https://www.youtube.com/watch?v=G4tNSnIE_lY&list=PLlD7n_T-mUjUuO7cW2TmmdXjxwaEqveE7
and my video: https://www.youtube.com/watch?v=l18z4x6RMfY&feature=youtu.be
you can choose your webcam if insted of number Videocapture();
add file weights, cfg, names in forder "net46"
Sorry for my bad English.

**Comment by AlievR** [comment]
Thank you very much for your help.
Does the program work fast or is it a long time?



>Вторник, 11 июня 2019, 18:52 +03:00 от tt20496 <notifications@github.com>:
>
>>@tt20496 , maill:  raslkrut5@mail.ru
>>Thanks for the help.
>i'm newbie so I follow this video to finish project:
>Capture EmguCV:  https://www.youtube.com/watch?v=MXjM4iN261s
>Yolo Detection:  https://www.youtube.com/watch?v=G4tNSnIE_lY&list=PLlD7n_T-mUjUuO7cW2TmmdXjxwaEqveE7
>and my video:  https://www.youtube.com/watch?v=l18z4x6RMfY&feature=youtu.be
>you can choose your webcam if insted of number Videocapture();
>add file weights, cfg, names in forder "net46"
>Sorry for my bad English.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
� услан Алиев

**Comment by AlievR** [comment]
Everything is recognized correctly, but the calculations are performed for a very long time. How can I speed up the program?

**Comment by tt20496** [comment]
> Everything is recognized correctly, but the calculations are performed for a very long time. How can I speed up the program?

Try to use EmguCV cuda, i think it's faster
