### ISSUE TITLE
Multiple Object Detection

### ISSUE THREAD

**Issue by MacIzm** [AlturosDestinations/Alturos.Yolo#10]
Hi, I'm new to using YOLO and I wanted to ask did this C# version of Yolo only suppose to detect one object/person in an image? 

Looking at the example it shows multiple detections. & running my example one detects one image.

Help?

**Comment by tinohager** [comment]
Yolo can detect multiple object on an image. The hardcoded limit of this library is 1000 objects for an image. If the detection works not perfect on your image try to switch to yolo3 dataset. Also you can train your own dataset if you have special objects.

**Comment by MacIzm** [comment]
Hey, I don't think I was being specific with what I meant about the detection. I was referring to the actual drawing of the bounding boxes. When it returns its index and tagged image data by the .Analyse() method it only draws one box.
