### ISSUE TITLE
Any plans to support face recognition?

### ISSUE THREAD

**Issue by espinosaluis** [AlturosDestinations/Alturos.Yolo#102]
Thanks for you great work on this wrapper.
I've read that Yolo also supports face recognition. Do you plan to add that eventually?

Regards

**Comment by tinohager** [comment]
There are special forums that have specialized in this area. Our base does not currently offer support for this application. More Information about the base you can found here https://github.com/AlexeyAB/darknet

**Comment by espinosaluis** [comment]
Ok. Thanks for the information.

**Comment by tinohager** [comment]
Here is a similar question https://github.com/AlexeyAB/darknet/issues/4833
