### ISSUE TITLE
Which version of Cuda?

### ISSUE THREAD

**Issue by BergChristian** [AlturosDestinations/Alturos.Yolo#104]
Hi!

In the nuget package it says 10.1 but on this page their is a link to 10.2. Which one should I install?

Best
Christian

**Comment by tinohager** [comment]
10.2 ist the right one

**Comment by tinohager** [comment]
i have update the readme thanks, https://github.com/AlturosDestinations/Alturos.Yolo/blob/master/src/Alturos.Yolo/readme.txt
