### ISSUE TITLE
DllNotFoundException: Microsoft Visual C++ 2017 Redistributable (x64)

### ISSUE THREAD

**Issue by TadaWasRaped** [AlturosDestinations/Alturos.Yolo#108]
For some reason I keep getting this error. Started to happen after I resetted my pc and can't find a fix any idea?

**Comment by LuckyLeeee** [comment]
Got the same problem when Install through NuGet and still can't manage how to fix this :((

**Comment by nguyenanhtuan1008** [comment]
Same problem in my pc. I get this error when I run in my pc. Before one month ago worked fine. I'm trying install through NuGet lastest version then build but in references didn't show Alturos.Yolo like before. Then I'm trying to downgrade this to 2.6.3 then got this problem.

**Comment by bernhardpetautschnig** [comment]
fixed with https://github.com/AlturosDestinations/Alturos.Yolo/issues/111
