### ISSUE TITLE
Unable to load DLL x64\yolo_cpp_dll_gpu.dll

### ISSUE THREAD

**Issue by ycshu086** [AlturosDestinations/Alturos.Yolo#11]
Hi, 

It seems several modules (get_device_count, get_device_name) in yolo_cpp_dll_gpu.dll are missing. Could you please take a look? The cpu version works fine in the wrapper. https://www.youtube.com/watch?v=wChPfgpk-0k 

I tried to compile the dll by myself based on https://github.com/AlexeyAB/darknet, but it never works in the wrapper. Any tricks there? My compiled dll (with OpenCV and GPU) can be successfully called by another C++ project.

**Comment by tinohager** [comment]
Which operating system you are use? Have you install cuda and cudnn? Is you graphic card from nvidia?

**Comment by ycshu086** [comment]
Windows Server 2016. Cuda (v8) and cudnn both installed and works fine in other projects. Yes, I am using nvidia GPU. 

Maybe you can provide more details on how you compile the dll on your side (yolo code version, modifications, settings etc.) so that I can try it by myself?

**Comment by tinohager** [comment]
I have no changes on the code, only some changes on the project files..

**darknet.sln**
![image](https://user-images.githubusercontent.com/8215186/46175653-ff687780-c2ac-11e8-94cd-762121a151b1.png)

**yolo_cpp_dll.vcxproj**
![image](https://user-images.githubusercontent.com/8215186/46175745-49515d80-c2ad-11e8-876e-1ef843a4eb66.png)

**Comment by ycshu086** [comment]
Not sure why the compiled gpu dll doesn't work for me, but I managed to compile one by myself by setting OPENCV; GPU; CUDNN; in preprocessor definitions in project yolo_cpp_dll. Thanks.

**Comment by tinohager** [comment]
Have you only add CUDNN in the second try?

**Comment by ycshu086** [comment]
What was missing is "OPENCV". My dll was previously called in another C++ project where it has preprocessor directives "#define OPENCV", so everything is fine. However, when you call the dll in C#, it seems we need to make sure preprocessor definitions are set in the C++ project before dll was compiled.
