### ISSUE TITLE
Exception thrown: 'Alturos.Yolo.YoloInitializeException' in Alturos.Yolo.dll

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [AlturosDestinations/Alturos.Yolo#111]
I got this error. How to fix this?

**Comment by nguyenanhtuan1008** [comment]
![Untitled](https://user-images.githubusercontent.com/36155295/77612329-3d5e5e80-6f6b-11ea-9c2c-5e59ae982384.png)

**Comment by nguyenanhtuan1008** [comment]
![Untitled](https://user-images.githubusercontent.com/36155295/77612498-a9d95d80-6f6b-11ea-8a46-f74443217a0f.png)

**Comment by bernhardpetautschnig** [comment]
Version 3.0.6-alpha fixes the problem
