### ISSUE TITLE
What do you mean "Version 3.0.6-alpha fixes the problem"?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [AlturosDestinations/Alturos.Yolo#113]
So sorry for this stupid question, but I didn't understand what do you mean about 3.0.6. Are you talking about NuGet or what? Sorry but pls explain more.

Version 3.0.6-alpha fixes the problem

_Originally posted by @bernhardpetautschnig in https://github.com/AlturosDestinations/Alturos.Yolo/issues/111#issuecomment-604435569_

**Comment by nguyenanhtuan1008** [comment]
Solved it!

**Comment by Albert2020666** [comment]
Hi, 
Do you mind explaining how you did solve it? I don't quite understand Version 3.0.6-alpha fixes the problem either...

Thank you.

**Comment by Albert2020666** [comment]
solved #119
