### ISSUE TITLE
Microsoft Visual C++ Redistributable har been update to a version that the YoloWrapper does not match

### ISSUE THREAD

**Issue by tarnow74** [AlturosDestinations/Alturos.Yolo#119]
Microsoft Visual C++ Redistributable har been update to a version that the YoloWrapper does not match. So the Wrapper thows an exception as if Microsoft Visual C++ Redistributable is not installed.

**Comment by bernhardpetautschnig** [comment]
Please use the latest Alturos.Yolo version 3.0.6-alpha. It supports the latest Mircrosoft Visual C++ Redistrutable

**Comment by IharrYeuseenka** [comment]
I have the same error. I use Alturos.Yolo. A in NuGet only 2.6.4 is available. I need for C#. Could you please explain how to find 3.0.6-alpha and add to the solution.

**Comment by IharrYeuseenka** [comment]
I used console (downloaded Yolo 3.0.6-alpha) but anyway I have new error  - "Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
