### ISSUE TITLE
solution for older computer with sse2 instruction set

### ISSUE THREAD

**Issue by terryll** [AlturosDestinations/Alturos.Yolo#12]
Thanks for sharing the program. 
The program work nicely on newer computer. It does not work on older computer with sse2 instruction set (don't have avx2). I'm just wondering if you have a quick solution for this case.

**Comment by terryll** [comment]
Thanks for the quick respond.
I try an older version from nuget. There are some function compatibility call variation on detection function call. Is there way to access older version of the package on GitHub ?
Thanks.

**Comment by tinohager** [comment]
I have not change the wrapper (c#) only change the c++ dll and this dlls are available in the nuget packages. Nuget allow download preview packages you can unzip a nupck with 7zip.

**Comment by terryll** [comment]
Thank a lot. It work.
 I just copy DLL ( yolo_cpp_dll_cpu.dll, yolo_cpp_dll_gpu.dll)and lib (Alturos.Yolo.dll)from the version 2.1.0 from nuget.
