### ISSUE TITLE
DELL not found on GPU

### ISSUE THREAD

**Issue by terryll** [AlturosDestinations/Alturos.Yolo#13]
When  running on GPU, I got message:
System.DllNotFoundException: 'Unable to load DLL 'x64\yolo_cpp_dll_gpu.dll': 
on line:  var deviceCount = GetDeviceCount();
The DELL is there.

I have CUDA 9.1 and cudnn-9.1 installed. Do I need to change it to the exact same version?
Thanks

**Comment by tinohager** [comment]
I don't know. Try to install 9.2 and send me a feedback please.

**Comment by terryll** [comment]
Installing CCUDA 9.2 take care the problem. Thanks.
