### ISSUE TITLE
Question about Converting Opencv mat to imageData

### ISSUE THREAD

**Issue by terryll** [AlturosDestinations/Alturos.Yolo#14]
This program make it a lot easier for me to incorporate the yolov3 tiny into my c# project. Thanks a lot.
My images from video is in Mat format. What is the best way to convert Mat image to imageData to be used in "yoloWrapper.Detect(imageData);".

Do you have a function that use Mat as input?
I notice the function in yoloWrapper.cs:
        [DllImport(YoloLibraryGpu, EntryPoint = "detect_mat")]
        internal static extern int DetectImageGpu(IntPtr pArray, int nSize, ref BboxContainer container);

**Comment by tinohager** [comment]
No i have no function for mat as input. Maybe this can help you... https://stackoverflow.com/questions/37540750/how-can-i-convert-mat-to-bitmap-using-opencvsharp

**Comment by terryll** [comment]
Thanks for the link.
It work. However, it not efficient. Image go from Mat to bitmap on drive, and  than call the bitmap file used up more processing time.
I found a more direct way of passing image to yolo more directly.
OpenCV have a function that convert image to imageData.
eg:   byte[] imageData = inputImage.ToBytes();
       items = mYoloWrapper.Detect(imageData).ToList();
