### ISSUE TITLE
It does not work on the RTX3060TI.

### ISSUE THREAD

**Issue by D3VL5H** [AlturosDestinations/Alturos.Yolo#162]
How can I use it on RTX3060TI?
I used Cuda10.2 and Cudn7.6.5.

**Comment by BergChristian** [comment]
What happens?

**Comment by BergChristian** [comment]
I experienced the same problems on a 3080 card and found this:

https://forums.developer.nvidia.com/t/rtx3080-run-yolo-no-response/156160
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

It seems that the 3000 series does. To support CUDA 7 but only 8.. but darknet is not supporting cuda 8. So until darknet solves that problem, we are stuck with this, as far as I understand it.

Damn it.

Christian

**Comment by D3VL5H** [comment]
Got it. Thanks!
