### ISSUE TITLE
 Is the CUDA version limited?

### ISSUE THREAD

**Issue by z3rO1997** [AlturosDestinations/Alturos.Yolo#167]
Is the only CUDA version 10.2 available?
I want to use 11.1, is it possible?

**Comment by zgabi** [comment]
If you can build the native yolo library (https://github.com/AlexeyAB/darknet) then you can repace the 
src\Alturos.Yolo\dependencies\win\yolo_cpp_dll_cpu.dll 
and 
src\Alturos.Yolo\dependencies\win\yolo_cpp_dll_gpu.dll 
files and it should work with newer CUDA.

I tried it, but the build was failing in my machine. I did not spent too much time on it.

**Comment by z3rO1997** [comment]
Thanks for answering

I didn't waste any more time and decided to just use CUDA 10.2ver
