### ISSUE TITLE
Box coordinate confusion

### ISSUE THREAD

**Issue by DaviesCooper** [AlturosDestinations/Alturos.Yolo#184]
I'm probably confused about this so this is more for clarification than to indicate an issue with the code.

As far as I can from Yolo's documentation, Yolo should be return for an object some X, Y, W, H values. Apparently these correspond to the center x coordinate, the center y coordinate, and some ratio of width to height data. Your YoloItem class however has the method Center() which seems to imply that the X, and Y correspond to the top left of an object, as opposed to the center.

Could you please respond indicating what X, Y, Width, and Height specify with regards to a YoloItem?

Much appreciated!

**Comment by fanatidark** [comment]
the X and Y coordinates belong to the upper right corner of the detected box.
the width is the pixels to the right from the X coordinate.
The height is the pixels down from the Y coordinate.

**Comment by DaviesCooper** [comment]
Thanks a ton! I also assume you mean the top _left_ not top right, correct?

**Comment by fanatidark** [comment]
Yes, it is the upper left, I was wrong in the wording, excuse me
