### ISSUE TITLE
Attempted to read or write protected memory

### ISSUE THREAD

**Issue by Sodininkas** [AlturosDestinations/Alturos.Yolo#2]
Hello,

We are getting exception, when trying to use GPU:

An exception of type 'System.AccessViolationException' occurred in Alturos.Yolo.dll but was not handled in user code
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Using visual studio 2017, Cuda 9.2, emgu, and example code

**Comment by tinohager** [comment]
Have you installed a NVIDIA graphic device?
You can use this tool to check all dependenc are available http://www.dependencywalker.com/

**Comment by tinohager** [comment]
Have you more informations?
