### ISSUE TITLE
Exception thrown when try another set.

### ISSUE THREAD

**Issue by smarcosanderson** [AlturosDestinations/Alturos.Yolo#20]
Hi,

First, thanks for bringing Yolo to .Net

Well, I am facing a problem when testing in Windows 10.
The project runs smoothly if I use the code bellow.

`var configurationDetector = new ConfigurationDetector();`
`var config = configurationDetector.Detect();`
`using (var yoloWrapper = new YoloWrapper(config))`

However, if I try to use another pre-trained set, I got some errors.
It could be that I'm misunderstood how to use a pre-trained set, but I supposed, I only need to download the set and reference in the code, such as bellow.

`using (var yoloWrapper = new YoloWrapper("yolov2.cfg", "yolov2.weights", "coco.names"))`

I usually got this error when trying out with a yolov2 set.

Exception thrown at 0x00007FFD1C663C88 (yolo_cpp_dll_cpu.dll) in YoloTest.exe: 0xC0000005: Access violation reading location 0x0000000000000008.

Thanks,
Marcos

**Comment by tinohager** [comment]
Do you have use the download links on my github page for the other yolo data?

**Comment by smarcosanderson** [comment]
All the downloads I got from the Pre-Trained Dataset section in the home of this github page:

https://github.com/AlturosDestinations/Alturos.Yolo

**Comment by tarnow74** [comment]
I am having the same error trying to use other than the default configuration.  Also win10.
But love how easy it was the get the default config up and running. Thank you !!!

**Comment by tinohager** [comment]
I have run it also with other configs. But i check this in 2 weeks. I'm currently busy

**Comment by smarcosanderson** [comment]
Ok, thanks Tino...
If theres any tips/guide, I can try to help with that.

**Comment by tinohager** [comment]
I have updated the documentation so you can try again? (New config files)
