### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by benmertburge** [AlturosDestinations/Alturos.Yolo#21]
System.NullReferenceException  related to 'Alturos.Yolo.dll' when i try to open in gpu mode. cuda 9.2 and cudnn 7.1.4 are installed.  Im on windows 10. Star for your project!

**Comment by tinohager** [comment]
Can you check with this tool are all dependencies exists? Open every dll in the x64 folder. Collapse the tree and check is anything red.

http://www.dependencywalker.com/
