### ISSUE TITLE
Graphic device index out of range with quadro P600

### ISSUE THREAD

**Issue by abhishekg1396** [AlturosDestinations/Alturos.Yolo#22]

**Comment by tinohager** [comment]
Can you provide more details?

**Comment by abhishekg1396** [comment]
the getDeviceCount returns 0 and cannot detect the GPU.
cuda 9.2 and cudnn 7.1.4 are installed. I am using windows 10.

**Comment by tinohager** [comment]
Maybe a problem with the gpu device. I think to find the bug we need to implement more logging in the c++ dll. https://stackoverflow.com/questions/14038589/what-is-the-canonical-way-to-check-for-errors-using-the-cuda-runtime-api

**Comment by abhishekg1396** [comment]
First i installed the cuda 9.2 and was only running the exe file
and after it for debugging installed the mvs 2017 community edition 
so, the cuda was not integrated with the mvs can this be the cause of the problem

**Comment by abhishekg1396** [comment]
sorry for the delayed response

**Comment by abhishekg1396** [comment]
i currently dont have any system with gpu so i cannot determine if the above was the case or not
