### ISSUE TITLE
Problems with broken item.Type output

### ISSUE THREAD

**Issue by Wangsujeon** [AlturosDestinations/Alturos.Yolo#24]
There is a problem that the label data is read from the current YoloWrapper and stored in the list of Yoloitem, and the characters are broken at the time of printing.

**Comment by tinohager** [comment]
Can you describe the problem in more detail?

**Comment by Wangsujeon** [comment]
The output of Item.Type is broken. For example, when a person is recognized, the label Item.Type "person" is broken.
This is similar to what happens when encoding decoding is different.
Look at the attachment file here.
![default](https://user-images.githubusercontent.com/20777622/50091203-08366d00-024e-11e9-8f98-81ac9e6682f2.png)

When the chair is recognized as shown in the picture above, the character of Item.Type is broken.

**Comment by tinohager** [comment]
can you add your `.names` file?

**Comment by Wangsujeon** [comment]
I used coco.names in darknet.

**Comment by tinohager** [comment]
On this repository i have a the TestUI project, can you check the output with this tool too?

**Comment by Wangsujeon** [comment]
The example result well. However, you should attach the camera.

**Comment by tinohager** [comment]
Sorry I'm not following you.

**Comment by Wangsujeon** [comment]
Okey. Thank you for your reply.

**Comment by tinohager** [comment]
I dont understand on which position of my code you have the problem...
