### ISSUE TITLE
Cannot find pre-trained model in System.IO

### ISSUE THREAD

**Issue by Sythe2954** [AlturosDestinations/Alturos.Yolo#25]
I am trying to make an Object Detection program that detects objects inside an image. Whenever I build and run it, it throws the following Exception 
```System.IO.FileNotFoundException: 'Cannot found pre-trained model, check all config files available (.cfg, .weights, .names)'``` on this line `var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect();`

**Comment by tosinamuda** [comment]
where are you supposed to put these files? Like what directory

**Comment by tinohager** [comment]
In the main directory of your application.
