### ISSUE TITLE
x64\yolo_cpp_dll_gpu.dll not found, when gpu work

### ISSUE THREAD

**Issue by receptanilcengiz** [AlturosDestinations/Alturos.Yolo#26]
Hello I am using win 10 cuda 9.0  when I added to x64 folder cudnn64_7, I am facing  x64\yolo_cpp_dll_gpu.dll not found problem. What should I do?

**Comment by tinohager** [comment]
On the latest version cuda 10 is required.

**Comment by receptanilcengiz** [comment]
I tried it but result same

**Comment by receptanilcengiz** [comment]
should I change anything from project?

**Comment by tinohager** [comment]
Can you check with this tool are all dependencies exists? Open every dll in the x64 folder. Collapse the tree and check is anything red.

http://www.dependencywalker.com/

**Comment by receptanilcengiz** [comment]
thank you, I am trying now

**Comment by tinohager** [comment]
You are use the newest nuget package?

Some files are missing in your system (C:\program files\nvidia gpu computing toolkit\cuda\v10.0\bin\)
CUBLAS64_100.DLL
CURAND64_100.DLL
CUDART64_100.DLL

![image](https://user-images.githubusercontent.com/8215186/51085934-3d948480-1740-11e9-9a4d-965b250c908e.png)

**Comment by receptanilcengiz** [comment]
yes I installed using nuget package. if exist any other method, I can do. where can I get that file?

**Comment by receptanilcengiz** [comment]
actually I have
![image](https://user-images.githubusercontent.com/18572866/51086036-87866600-1752-11e9-94dd-76cf2217e54a.png)

**Comment by tinohager** [comment]
And you have installed Version 2.4.0?

**Comment by receptanilcengiz** [comment]
I think no
<packages>
  <package id="Alturos.Yolo" version="2.2.4" targetFramework="net461" />
  <package id="Alturos.YoloV2TinyVocData" version="1.0.0" targetFramework="net461" />
</packages>

**Comment by tinohager** [comment]
`update-package Alturos.Yolo`

**Comment by receptanilcengiz** [comment]
Installing Alturos.Yolo 2.3.0.
Adding package 'Alturos.Yolo.2.3.0' to folder 'C:\Users\RECEP\Documents\Visual Studio 2015\Projects\ObjectDetect\YoloObjectDetect\packages'
Added package 'Alturos.Yolo.2.3.0' to folder 'C:\Users\RECEP\Documents\Visual Studio 2015\Projects\ObjectDetect\YoloObjectDetect\packages'
Added package 'Alturos.Yolo.2.3.0' to 'packages.config'
Successfully installed 'Alturos.Yolo 2.3.0' to ObjectDetect
Removing package 'Alturos.Yolo 2.2.4' from folder 'C:\Users\RECEP\Documents\Visual Studio 2015\Projects\ObjectDetect\YoloObjectDetect\packages'
Removed package 'Alturos.Yolo 2.2.4' from folder 'C:\Users\RECEP\Documents\Visual Studio 2015\Projects\ObjectDetect\YoloObjectDetect\packages'

**Comment by receptanilcengiz** [comment]
but not 2.4.0

**Comment by tinohager** [comment]
and its works with 2.3.0?

**Comment by receptanilcengiz** [comment]
error changed
my sistem i7 7700K
GPU:GTX1050TI
![image](https://user-images.githubusercontent.com/18572866/51086235-404da480-1755-11e9-9fb8-efc9ca2b33b9.png)

**Comment by tinohager** [comment]
Please share your code of `YoloWrapper`

**Comment by receptanilcengiz** [comment]
![image](https://user-images.githubusercontent.com/18572866/51086272-e5687d00-1755-11e9-99ed-3fafc8dff61d.png)
you mean this?

**Comment by tinohager** [comment]
Check if you have installed the newest graphic driver, and check if you have installed cuDNN v7.4.2.24

**Comment by receptanilcengiz** [comment]
Yes because of uninstalling cuda9.0, driver also uninstalled. for now no error but detection time didnt decreased. still 620ms with gpu and without gpu same

**Comment by tinohager** [comment]
Sorry then I don't know what's wrong with your system.

**Comment by receptanilcengiz** [comment]
in your system how many ms takes with gpu?

**Comment by tinohager** [comment]
have you test with my test images in the repo or with your own ones?

**Comment by receptanilcengiz** [comment]
both of them are same
![image](https://user-images.githubusercontent.com/18572866/51087266-24043480-1762-11e9-9659-05efa4a4ea1b.png)

**Comment by tinohager** [comment]
And you are sure the detection system is gpu? YoloWrapper.DetectionSystem ?

**Comment by receptanilcengiz** [comment]
no you didnt say anything about this. I sent my code above. where and how will I add this code line?

**Comment by tinohager** [comment]
You can contact https://github.com/AlexeyAB/darknet to ask the dll in the background.

**Comment by receptanilcengiz** [comment]
after 4-5 start stop program, it gives this error and unless restart pc, I cant start program
![image](https://user-images.githubusercontent.com/18572866/51088763-dfce5f80-1774-11e9-8cd9-c2337aeeb6de.png)

**Comment by tinohager** [comment]
You can check the memory of the gpu with this tool https://github.com/AlturosDestinations/Alturos.Yolo#debugging-gpu-tool

Dont stop the process is better for the gpu...
