### ISSUE TITLE
Where can I find class probability ?

### ISSUE THREAD

**Issue by died** [AlturosDestinations/Alturos.Yolo#28]
As we know, YOLO result first 5 value are x,y,w,h and confidence, rest are class probability, but in sample code `//items[0].Type -> "Person, Car, ..."` seems only give one class, not the value, so , where  or how can I get the value ?

**Comment by tinohager** [comment]
Which value?

**Comment by died** [comment]
for example, in yolov3, the output have 85 values(0~84), at 5~84th means each classes probability, the probability different to confidence, sometimes it way lower than confidence (or higher).
Can we get the value in Alturos.Yolo ?

**Comment by tinohager** [comment]
The output of Alturos.Yolo is this model [bbox_t ](https://github.com/AlexeyAB/darknet/blob/master/include/yolo_v2_class.hpp) of https://github.com/AlexeyAB/darknet

**Comment by died** [comment]
I mean the **score** section in [yolo](https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/examples/detector.c#L186), or `dets[i].prob[j]` => the prob value.

**Comment by tinohager** [comment]
i think currently is not available

**Comment by died** [comment]
OK, got it, thank you.
