### ISSUE TITLE
train image

### ISSUE THREAD

**Issue by himsha** [AlturosDestinations/Alturos.Yolo#29]
is there is any provision to train object?

like i want to train one/two/three axle truck, so how to do this?

**Comment by tinohager** [comment]
https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by tinohager** [comment]
We also work on an new tool for custom dataset [Alturos.ImageAnnotation](https://github.com/AlturosDestinations/Alturos.ImageAnnotation)

**Comment by moon341** [comment]
> We also work on an new tool for custom dataset [Alturos.ImageAnnotation](https://github.com/AlturosDestinations/Alturos.ImageAnnotation)

Is there any place where I can have guidance about training the tool using custom dataset and then use it in my c# client using alturos? I searched myself on internet but I couldn't find any guidance to use custom dataset trained yolo in c# client using alturos packages. Or the alturos only provide the service to use tool trained only on their benchmark datasets?
