### ISSUE TITLE
Crash upon using 'Detect' with a byte array.

### ISSUE THREAD

**Issue by iMeteox** [AlturosDestinations/Alturos.Yolo#3]
Hello,

I've managed to use this version of YOLO on Unity (quite easily thanks to the wrapper and other classes), and I can easily operate the algorithm on an existing picture like Motorbike1.jpg when I use the 'Detect' function of the YoloWrapper class with the path parameter as a string. 

When I use the 'Detect(byte[] imageData)' version of the function however, the editor crashes. I've narrowed the bug all the way down to lines 198 to 203 of the file YoloWrapper.cs, which means that it comes from when I call the DLL. I'm pretty sure the problem comes from my imageData byte array, since it's the parameter I give to the 'Detect' method.

Here's how I create the byte array that I send to the YoloWrapper for detection: 

    public IEnumerable<YoloItem> Detect()
    {
        return yoloWrapper.Detect(Color32ArrayToByteArray(webCamTexture.GetPixels32()));
    }

    private static byte[] Color32ArrayToByteArray(Color32[] colors)
    {
        if (colors == null || colors.Length == 0)
            return null;

        int lengthOfColor32 = Marshal.SizeOf(typeof(Color32));
        int length = lengthOfColor32 * colors.Length;
        byte[] bytes = new byte[length];

        GCHandle handle = default(GCHandle);
        try
        {
            handle = GCHandle.Alloc(colors, GCHandleType.Pinned);
            IntPtr ptr = handle.AddrOfPinnedObject();
            Marshal.Copy(ptr, bytes, 0, length);
        }
        finally
        {
            if (handle != default(GCHandle))
                handle.Free();
        }

        return bytes;
    }

In this code, the 'webCamTexture' variable is a 'WebCamTexture' from the UnityEngine, documentation here: https://docs.unity3d.com/ScriptReference/WebCamTexture.html

Any idea why the crash happens? Is it actually the way I create the byte array, or do I need to recompile / use another DLL?

Thanks in advance,

Maxime.

**Comment by tinohager** [comment]
I think your byte array contains invalid data. You must convert first the rgb data to an image.

https://stackoverflow.com/questions/47575438/convert-color32-array-to-byte-array-to-send-over-network/47576608#47576608

Am 10.08.2018 um 21:43 schrieb Maxime Morin Grandmont <notifications@github.com<mailto:notifications@github.com>>:

webCamTexture.GetPixels32()

**Comment by iMeteox** [comment]
Oh, that does make sense. Unfortunately, I still get a crash. This time, I've been able to find the log for the crash though. 

"
Stack Trace of Crashed Thread 17492:
0x00007FF9F8B24496 (mono) [f:\dd\vctools\crt_bld\SELF_64_amd64\crt\src\amd64\memcpy.asm:387] memcpy 
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 000000003A0C6A52)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 000000003A0C6A52)
0x000000003A0C6A52 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 00000000445E85B0)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 00000000445E85B0)
0x00000000445E85B0 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 00000000005FCF30)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 00000000005FCF30)
0x00000000005FCF30 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 0000000000897570)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 0000000000897570)
0x0000000000897570 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 000000003BAA7B60)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 000000003BAA7B60)
0x000000003BAA7B60 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 000000000004B000)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 000000000004B000)
0x000000000004B000 ((<unknown>)) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 0000000081F71020)
ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 0000000081F71020)
0x0000000081F71020 ((<unknown>)) (function-name not available)
"
My code is now:

    private IEnumerable<YoloItem> Detect()
    {
        return yoloWrapper.Detect(ExctractByteArrayFromWebcamTexture());
    }

    private byte[] ExctractByteArrayFromWebcamTexture()
    {
        Color32Array colorArray = new Color32Array();
        colorArray.colors = new Color32[webCamTexture.width * webCamTexture.height];
        webCamTexture.GetPixels32(colorArray.colors);
        return colorArray.byteArray;
    } 

Though If I change the return line of Detect() to: 
    return return yoloWrapper.Detect(Application.dataPath + "/yolo.jpg");
implying I have an image called "yolo.jpg" in the path, it works just right. The only bother is, I'm trying to make object detection in real time, and saving a picture over and over again is just too slow for the context.

I'll look further into it. The only thing I can think of is there might be an extra conversion needed.

**Comment by tinohager** [comment]
You can convert the image in memory and transfer direct witout write to disk.

**Comment by tinohager** [comment]
https://stackoverflow.com/questions/12495172/i-want-to-use-a-texture2d-as-a-system-drawing-bitmap

**Comment by iMeteox** [comment]
I got it working now! Thank you for your help! 
Here's the final piece of code for anyone that happens to have the same issue: 

    private IEnumerable<YoloItem> Detect()
    {
        Texture2D texture = ExctractTextureFromRawImage(rawImage);
        var imageData = ImageConversion.EncodeToJPG(texture);
        return yoloWrapper.Detect(imageData);
    }

    private Texture2D ExctractTextureFromRawImage(RawImage image)
    {
        Texture2D snap = new Texture2D(image.texture.width, image.texture.height);
        WebCamTexture currentTexture = (WebCamTexture)image.texture;
        snap.SetPixels(currentTexture.GetPixels());
        snap.Apply();
        return snap;
    }

Thanks a lot!

**Comment by tinohager** [comment]
Hi iMeteox, How to get to the detailed crash report?

**Comment by kutayatik** [comment]
Hi, i want to add Alturos.Yolo in my Unity Project. Everything is fine in visual studio 2017, but Unity Editor doesn't see Alturos.Yolo.

` Assets\Scripts\ObjectDetection.cs(4,7): error CS0246: The type or namespace name 'Alturos' could not be found (are you missing a using directive or an assembly reference?)`
