### ISSUE TITLE
Only 64bit processes allowed

### ISSUE THREAD

**Issue by valavakilian** [AlturosDestinations/Alturos.Yolo#30]
Hi. I was trying to use this package when I run into the following problem:

Error on_videoSource_NewFrame:
Only 64-bit processes are supported

Can someone please point me towards the right direction?
thank you

**Comment by valavakilian** [comment]
Sorry. Got it.

**Comment by TuanAnh207** [comment]
How did you solve this issue @valavakilian ?

**Comment by valavakilian** [comment]
It's not an issue. I believe this package works with a version of DarkNet that can only be implemented on a 64-bit processor. I needed to run this model on a 32 bit processor and it failed. I ended up using another model.
#31

**Comment by Miwwe** [comment]
I have 64-bit processor but i also get this error, no idea why

**Comment by tinohager** [comment]
Have you switch to 64bit in Visual Studio?
![image](https://user-images.githubusercontent.com/8215186/61857448-7d44e180-aec4-11e9-984f-2d222cb4730d.png)
