### ISSUE TITLE
Using yolov3 with coco

### ISSUE THREAD

**Issue by valavakilian** [AlturosDestinations/Alturos.Yolo#32]
Hello and thank you for your great work on .Net YOLO module. 
I am trying to run yolov3 with coco on my windows 10 in visual studio. I first tried using yolov2-tiny-voc and that work fine. However, I'm trying to have better detection so I decided to use yolov3. I downloaded the dependencies and I copied them into their proper folder so it is in the same place as yolov3-tiny-voc. this is my call for the function:
using (var yoloWrapper = new YoloWrapper("yolov3.cfg", "yolov3.weights", "coco.names"))
                {

                    bool fileExists2 = File.Exists(filePath);
                    lock (filePath)
                    {
                        if (fileExists2)
                        {
                            Console.WriteLine("Frame2 call");
                            var items = yoloWrapper.Detect(filePath);
                            //items[0].Type -> "Person, Car, ..."
                            //items[0].Confidence -> 0.0 (low) -> 1.0 (high)
                            //items[0].X -> bounding box
                            //items[0].Y -> bounding box
                            //items[0].Width -> bounding box
                            //items[0].Height -> bounding box

                            itemList = (List<Alturos.Yolo.Model.YoloItem>)items;
                            //Console.WriteLine(itemList);
                        }
                    }
                }
However, when I run this the screen appears just for a second but then disappears and the program exits. I believe it is able to detect the files fine as it isn't giving me the file-not-found exception.  This is the result of the last couple of lines on the command prompt:

 107 Type not recognized: [net]
Unused field: 'batch = 1'
Unused field: 'subdivisions = 1'
Unused field: 'width = 416'
Unused field: 'height = 416'
Unused field: 'channels = 3'
Unused field: 'momentum = 0.9'
Unused field: 'decay = 0.0005'
Unused field: 'angle = 0'
Unused field: 'saturation = 1.5'
Unused field: 'exposure = 1.5'
Unused field: 'hue = .1'
Unused field: 'burn_in = 1000'
Unused field: 'max_batches = 500200'
Unused field: 'policy = steps'
Unused field: 'steps = 400000,450000'
Unused field: 'scales = .1,.1'
 108 Layer before convolutional layer must output image.: No error
The program '[12588] streamer.exe' has exited with code 1 (0x1).

This error happens consistently in the layers 107 and 108.
Sorry if my question is long and doesn't make that much sense but I'm a beginner with Yolo and C#. Again, thanks a lot for your help.

**Comment by tinohager** [comment]
Have you use my config downloader?

**Comment by valavakilian** [comment]
yes I believe I have . I used the following code : 
var repository = new YoloPreTrainedDatasetRepository();
await repository.DownloadDatasetAsync("YOLOv3", ".");

And I was just able to use the YOLOv2 with coco without any problem.
Thank you

**Comment by tinohager** [comment]
I have create a fresh project and test it with no problems

![image](https://user-images.githubusercontent.com/8215186/52235958-cf1d8f00-28c5-11e9-8e13-2b151175010a.png)

**Comment by valavakilian** [comment]
Thank you very much. I will give it a try. But I think the yolov2 works pretty well for me . At least for now. I will post again if I can get the yolov3 to work on my system. probably a minor problem on my side.

Thanks a lot or your help
