### ISSUE TITLE
Alturos.Yolo DLLs send corrupted detection data under Unity

### ISSUE THREAD

**Issue by Armitage1982** [AlturosDestinations/Alturos.Yolo#33]
Hi,

I'm using Darknet inside Unity under Windows 10 as a DLLImport with good results but I found your implementation for .Net more interesting.

Unfortunately Alturos return incoherent values like -1941698683 as Object Class or 247879272759296.0 for confidence value.

It happens with both GPU & CPU version. I can't really tell much since there's no source for yolo_cpp_dll_cpu.dll & yolo_cpp_dll_gpu.dll.

I'm using the Unity 2018.3 with .NET 4.x equivalent runtime version & API Compatibility Level .NET 4.x with a Mono Scripting Backend (same result through IL2CPP).

Do you have any idea what could corrupt the data using a mono backend?

The only thing I changed is the DLL location inside the wrapper (I just remove « x64\ » or then I could not make it work inside the Unity Editor).

I read here that someone had already managed to use Alturos under Unity but for some reason I haven't succeeded yet.

DLLs & yolo config files work great with your UI example and I double checked the encoding & culture settings. 

Thanks

> HKEY_CLASSES_ROOT\Installer\Dependencies\VC,redist.x64,amd64,14.16,bundle
>     (Default)    REG_SZ    {5fb2083a-f3cc-4b78-93ff-bd9788b5de01}
>     Version    REG_SZ    14.16.27024.1
>     DisplayName    REG_SZ    Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27024

**Comment by tinohager** [comment]
![image](https://user-images.githubusercontent.com/8215186/52234610-5cf77b00-28c2-11e9-9fb2-fc6c448a837c.png)

I have test on my machine and the values looks good.

**Comment by tinohager** [comment]
The sources of `yolo_cpp_dll_cpu.dll` and `yolo_cpp_dll_gpu.dll`are available here. 

[tino.hager darknet](https://github.com/tinohager/darknet) and the [artifacts](https://ci.appveyor.com/project/tinohager/darknet/builds/22094760/artifacts)

**Comment by tinohager** [comment]
Another option would be to run the yolo process separately and communicate via a webapi

**Comment by Armitage1982** [comment]
It's something I think about too since we already need to build a webcam services.
Speed is not (yet) a prerequisite for this project.

**Comment by raulsf6** [comment]
Hi @Armitage1982, did you manage to get it working? I'm also stucked with this and I just can't keep working in my project without solving the issue!
