### ISSUE TITLE
Configuring the GPU

### ISSUE THREAD

**Issue by valavakilian** [AlturosDestinations/Alturos.Yolo#34]
Hello and sorry for asking so many question.
I'm trying to do inference on the GPU using the YOLOv2 as it takes about 1.7 seconds for each image at the moment ( I am running this on a video stream and I have object detection running in parallel with some other applications ). I believe I have cudnn and Cuda installed as I was able to detect them on the with the command prompt. I changed the yolowrapper to :
using (var yoloWrapper = new YoloWrapper("yolov2.cfg", "yolov2.weights", "coco.names", 1 , false))
I believe there is another step that I am missing in the process of getting the GPU to work with the code. Can you please help me with that ?
Thanks you for your support

**Comment by tinohager** [comment]
Hi, have you done all of the steps here? https://github.com/AlturosDestinations/Alturos.Yolo/blob/master/README.md#gpu-requirements-optional

I am also happy to get a star for this project 😄

**Comment by tinohager** [comment]
Set gpu parameter to 0 instead of 1

**Comment by valavakilian** [comment]
Thank you very much. That basically did the trick.
