### ISSUE TITLE
Create own data set by using VoTT: Visual Object Tagging Tool 1.5

### ISSUE THREAD

**Issue by Adamszsz** [AlturosDestinations/Alturos.Yolo#35]
I created my own dataset. I've clicked over 2,000 pictures using the VoTT program: Visual Object Tagging Tool 1.5.
I clicked the "export tags" button and saved.
I created a folder with: yolo-obj.cfg plus the "data" folder with data obj.names, obj.data

I would like to use the masterpiece created by me now.
How can I use this? I know that you have to put it somehow in DATASET but do not know how.
MY code looks like 

```
var configurationDetector = new ConfigurationDetector ();
  var config = configurationDetector.Detect ();
    using (var yoloWrapper = new YoloWrapper (config))
              {
               using (MemoryStream ms = new MemoryStream ())
               {
                 pictureBox1.Image.Save (ms, ImageFormat.Png);
                 screen_full_ekranu.Save (ms, ImageFormat.Png);
                 var items = yoloWrapper.Detect (ms.ToArray ());
                 yoloItemBindingSource.DataSource = items;
               }
              }
```

I need to create yoloitemBindingsource and replace with that how can i do that?
Any suggestion , tutorial would help. 
Thanks!.

**Comment by tinohager** [comment]
This library can only use pretrained datasets. If you have the raw data you must follow this documentation https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

**Comment by Adamszsz** [comment]
But is anywhere a tutorial how should correctly do that ( video ) bacause this documentation is unreadable ;/

**Comment by tinohager** [comment]
Maybe this is better i have not checked... https://medium.com/@manivannan_data/how-to-train-yolov3-to-detect-custom-objects-ccbcafeb13d2

**Comment by Adamszsz** [comment]
As i understand after this steps i just gonna create own data set and can use it later in my code right?

**Comment by tinohager** [comment]
Yes

**Comment by Adamszsz** [comment]
Would be great to see video on youtube step by step how to do that and later use it in code and check results. :)

**Comment by tinohager** [comment]
You make a video? 😃

**Comment by Adamszsz** [comment]
When i gonna know how to do train own dataset then implement it in code i can do it.

**Comment by tinohager** [comment]
We also work on an new tool for custom dataset [Alturos.ImageAnnotation](https://github.com/AlturosDestinations/Alturos.ImageAnnotation)
