### ISSUE TITLE
Can i use 2 detectors in my project?

### ISSUE THREAD

**Issue by arnoldhoward** [AlturosDestinations/Alturos.Yolo#36]
Hi, dear.
I met the issue in using multi detectors.
I am working alpr, first i should detect plate region and then detect each character in plate.
So, i should use 2 weights, 2 conf, 2 names files in my project.
For this, i imported the Alturos.Yolo project to my project and created 2 YoloWrapper objects.
But i got the issue, bcz although i made 2 YoloWrapper objects, last Yolowrapper configuration saved.
I'd like to u help me.
Thanks.

**Comment by tinohager** [comment]
Can you share an example code?

**Comment by arnoldhoward** [comment]
var detect_cfg = Path.Combine(LOCATION, DETECT_CFG);
            var detect_weight = Path.Combine(LOCATION, DETECT_WEIGHT);
            var detect_names = Path.Combine(LOCATION, DETECT_NAMES);
            this.detect_yoloWrapper = new Alturos.Yolo.YoloWrapper(detect_cfg, detect_weight, detect_names, ignoreGpu: ignoreGpu);

            var recog_cfg = Path.Combine(LOCATION, RECOG_CFG);
            var recog_weight = Path.Combine(LOCATION, RECOG_WEIGHT);
            var recog_names = Path.Combine(LOCATION, RECOG_NAMES);
            this.recog_yoloWrapper = new Alturos.Yolo.YoloWrapper1(recog_cfg, recog_weight, recog_names, ignoreGpu: ignoreGpu);

... ... ...
items = this.detect_yoloWrapper.Detect(data).ToList();

// I accessed detect function of detect_yoloWrapper, but result isnot for detect_yoloWrapper.
it is for recog_yoloWrapper.

**Comment by randellhodges** [comment]
The darknet yolo c++ dll exposes a static instance of the detector. As it stands, you cannot use 2 detectors. You might be able to spin up a new AppDomain and load an instance in each AppDomain (a thread isn't enough), but then you'd have to deal with marshaling data between domains.

I will submit a pull request to darknet later that'll remove the limitation. Then the YoloWrapper can track the instance and let you create as many as you have resources, assuming my code is correct.

https://github.com/AlturosDestinations/Alturos.Yolo/issues/38#issuecomment-479621039

**Comment by tinohager** [comment]
I have add a new webservice project. You can start this project twice and load different configurations. `Alturos.Yolo.WebService`

In the `app.config` you can set the service port.
You can test it with the swagger interface `http://localhost:8080/swagger`
