### ISSUE TITLE
Can i use to train Yolov3 with my own custom dataset?

### ISSUE THREAD

**Issue by Oskop** [AlturosDestinations/Alturos.Yolo#37]

**Comment by tinohager** [comment]
Yes you can train yolov3, check the documentation here https://github.com/AlexeyAB/darknet

**Comment by tinohager** [comment]
We also work on an new tool for custom dataset [Alturos.ImageAnnotation](https://github.com/AlturosDestinations/Alturos.ImageAnnotation)
