### ISSUE TITLE
multi detection simultaneously

### ISSUE THREAD

**Issue by arnoldhoward** [AlturosDestinations/Alturos.Yolo#38]
I have 4 camera on my system and I want to detect object from this cameras simultaneously. 
For each detection for one camera, i should detect 2 times with different configuration and weight. 
How can I achieve this? or at least, is it possible?

**Comment by tinohager** [comment]
I think it is possible but i must change before some logic of the code. Have you try with to separated processes?

**Comment by arnoldhoward** [comment]
I am going to use 4 threads, so one thread per one camera.
And for 2 times detection per one camera, 
currently, i made the YoloWrapper1 class that copied YoloWrapper class,  and imported the Yolocpp1.dll (that copied Yolocpp.dll).
And detected the object 2 times for one camera using Yolowrapper, Yolowrapper1 class.
But this way is too troublesome.
Maybe in yolocpp. dll, only allow one instance for one weight, one configuration.
I'd like to u add the function for multi instance.

**Comment by tinohager** [comment]
I have check the current code, but i think currently is not easy viable. You must split your code into individual processes.

**Comment by randellhodges** [comment]
I'm not sure if it would be accepted, but I have local modifications to darknet that removes the static instance of the detector inside the dll. I'll submit a pull request later this week.

The init method returns a pointer from the detector. You'd have to pass it to the detect method and to the clean method. By tracking the pointer yourself (aka, in the C# code) you could spawn as many instances of the detector as you have resources to handle.

I am a C++ newb, so I'm not sure how "correct" my change is, but I'll post it over on darknet later anyway.

**Comment by randellhodges** [comment]
I submitted a pull request. If accepted, with some modifications to your version of the YoloWrapper (see my update to the one in the pull request), each instance of the YoloWrapper would have it's own backing Darknet detector.

https://github.com/AlexeyAB/darknet/pull/2830

**Comment by jonaschan** [comment]
Hi all! Is there an update on the progress of the current pull request for multi detection?

Hi @randellhodges, have you manage to find out what the maximum number of models you can run with your current solution?

Thanks all!

**Comment by tinohager** [comment]
What is the reason for run multi detectors?

**Comment by jonaschan** [comment]
Well, one reason i'm using this is for daisy chaining multiple models.

**Comment by tinohager** [comment]
Dispose and Initialize is to slow?

**Comment by jonaschan** [comment]
Well, essentially i would like to daisy chain a few Yolo models as follows:
Image => Model 1 => Crop image where detection was found => Model 2 => Repeat

The image is coming directly from a camera feed. All this are running at GPU speeds.

However, I wouldnt know how would disposing and reinitialising for each model would affect the speed

**Comment by tinohager** [comment]
I have add a new webservice project. You can start this project twice and load different configurations. `Alturos.Yolo.WebService`

In the `app.config` you can set the service port.
You can test it with the swagger interface `http://localhost:8080/swagger`

**Comment by MarcelMeurer** [comment]
Take a look here (workaround): https://github.com/AlturosDestinations/Alturos.Yolo/issues/68#issuecomment-521122054

**Comment by jalaldev1980** [comment]
Hi,
I am detecting object using 2 cameras .. one code..my question
is it possible to give the object on both camera same detection ID (in other words; identify the same object on both cameras?)
thank you in advance

**Comment by tinohager** [comment]
Yolo can only detect a object type. Your logic must calculate that the position of camera1 match the position of camera2

**Comment by George3256** [comment]
> Ну, по сути, я хотел бы объединить несколько моделей Yolo следующим образом:
> Изображение => Модель 1 => Кадрировать изображение, где было обнаружено обнаружение => Модель 2 => Повторить
> 
> Изображение поступает прямо с камеры. Все это работает на скоростях GPU.
> 
> Тем не менее, я бы не знал, как утилизация и повторная инициализация для каждой модели повлияет на скорость

Please describe in more detail how to do this. This solution would help me.
