### ISSUE TITLE
Doesn't detect visual c++ 2017 redistributable

### ISSUE THREAD

**Issue by Jeffmagma** [AlturosDestinations/Alturos.Yolo#39]
I kept getting the error `DllNotFoundException: Microsoft Visual C++ 2017 Redistributable (x64)`, so I decompiled the source and saw that it was just looking under the registry key `Installer\\Dependencies\\VC,redist.x64,amd64,14.16,bundle`, but it seems that mine is located in `Installer\\Dependencies\\VC,redist.x64,amd64,14.20,bundle`, is it possible to make it check for both?

**Comment by tinohager** [comment]
I check this next week...

**Comment by PoH98** [comment]
Sorry but newer version is now contains Installer\\Dependencies\\VC,redist.x64,amd64,14.21, bundle... can you update it please? (Or maybe use some other method for finding?)

**Comment by tinohager** [comment]
@PoH98  i have publish a new verison

**Comment by Yuki-Nagato** [comment]
I am sorry, but the `DisplayName` of `VC,redist.x64,amd64,14.21,bundle` begins with "`Microsoft Visual C++ 2015-2019 Redistributable (x64)`" in my system, so I think you should consider whether it is correct to just check `displayName.StartsWith("Microsoft Visual C++ 2017 Redistributable (x64)")`.

**Comment by PoH98** [comment]
oh, didnt seen that carefully, just checked and yes with name differently

**Comment by b6land** [comment]
Hi, in new version of Visual C++ Redistributable (2015-2019 bundle), the register key is:
`HKEY_CLASSES_ROOT\Installer\Dependencies\VC,redist.x64,amd64,14.22,bundle`
and the value of 'DisplayName' is:
`Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.22.27821`
Hope it can be added to `YoloWrapper.cs`.

Currently I added register key and value in the `YoloWrapper.cs` to Registry, and runs well.

**Comment by tinohager** [comment]
[add an update for new c++ package](https://github.com/AlturosDestinations/Alturos.Yolo/commit/e70d3d8fc4698c8a7d851ac6481daab67a7f60fc)
