### ISSUE TITLE
Invalid image data, wrong image format

### ISSUE THREAD

**Issue by JohnPekl** [AlturosDestinations/Alturos.Yolo#42]
How can I process an image with **_PixelFormat.Format32bppPArgb_**? or any other PixelFormat types.

It seems that you limited input image format in the **ImageAnalyzer** class.
```
var bmp = Encoding.ASCII.GetBytes("BM");  //BMP
var png = new byte[] { 137, 80, 78, 71 }; //PNG
var jpeg = new byte[] { 255, 216, 255 };  //JPEG
```
Furthermore, if I have a pointer of an image data IntPtr, how can I proceed with this pointer? In detail, the static method **_DetectImageCpu(IntPtr pArray, int nSize, ref BboxContainer container);_** has a IntPtr input. If I have a pointer I do not need to copy my image data in **_public IEnumerable<YoloItem> Detect(byte[] imageData)_**.

I have tried with the following modified method but it throws an exception.

> Exception thrown: 'System.Runtime.InteropServices.SEHException' in Alturos.Yolo.dll
> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
>    at Alturos.Yolo.YoloWrapper.DetectImageGpu(IntPtr pArray, Int32 nSize, BboxContainer& container)
>    at Alturos.Yolo.YoloWrapper.Detect(IntPtr pnt, Int32 length) in DetectImageGpu(pnt, length, ref container);

```
        public IEnumerable<YoloItem> Detect(IntPtr pnt, int length)
        {
            //if (!this._imageAnalyzer.IsValidImageFormat(imageData))
            //{
            //    throw new Exception("Invalid image data, wrong image format");
            ////}

            var container = new BboxContainer();
            //var size = Marshal.SizeOf(imageData[0]) * imageData.Length;
            //var pnt = Marshal.AllocHGlobal(size);

            try
            {
                // Copy the array to unmanaged memory.
                //Marshal.Copy(imageData, 0, pnt, imageData.Length);
                var count = 0;
                switch (this.DetectionSystem)
                {
                    case DetectionSystem.CPU:
                        count = DetectImageCpu(pnt, length, ref container);
                        break;
                    case DetectionSystem.GPU:
                        count = DetectImageGpu(pnt, length, ref container);
                        break;
                }

                if (count == -1)
                {
                    throw new NotImplementedException("C++ dll compiled incorrectly");
                }
            }
            catch (Exception exception)
            {
                return null;
            }
            finally
            {
                // Free the unmanaged memory.
                //Marshal.FreeHGlobal(pnt);
            }

            return this.Convert(container);
        }
```

Note: **CopyMemory()** native method is faster than **Marshal.Copy** as my experience.

**Comment by tinohager** [comment]
Sorry but i have not check it with a pointer, you can try to contact the [maintainer](https://github.com/AlexeyAB/darknet) of AlexeyAB/darknet. On which place you want change to CopyMemory?

**Comment by JohnPekl** [comment]
Thanks for your response.
Regarding _MemoryCopy_, whenever you use this **Marshal.Copy(imageData, 0, pnt, imageData.Length);**, you can replace that statement to _MemoryCopy_.

I used to declare the method as following
```
[DllImport("kernel32.dll", EntryPoint = "CopyMemory", SetLastError = false)]
private static extern void CopyMemory(IntPtr dest, IntPtr src, int count);
```

**Comment by tinohager** [comment]
But this code only work on windows machines and not on linux?

**Comment by tinohager** [comment]
Maybe this is a better solution? https://docs.microsoft.com/en-us/dotnet/api/system.buffer.memorycopy?redirectedfrom=MSDN&view=netframework-4.7.2#overloads

**Comment by tinohager** [comment]
I tried to use `Buffer.MemoryCopy` (Activate `Allow unsafe code`). I have not noticed any performance improvement.

    public IEnumerable<YoloItem> Detect(byte[] imageData)
    {
        if (!this._imageAnalyzer.IsValidImageFormat(imageData))
        {
            throw new Exception("Invalid image data, wrong image format");
        }

        var container = new BboxContainer();
        var size = Marshal.SizeOf(imageData[0]) * imageData.Length;
        var pnt = Marshal.AllocHGlobal(size);

        try
        {
            //Copy the array to unmanaged memory.
            unsafe
            {
                fixed (byte* first = &imageData[0])
                {
                    Buffer.MemoryCopy(first, pnt.ToPointer(), size, size);
                }

            }
            //Marshal.Copy(imageData, 0, pnt, imageData.Length);
            var count = 0;
            switch (this.DetectionSystem)
            {
                case DetectionSystem.CPU:
                    count = DetectImageCpu(pnt, imageData.Length, ref container);
                    break;
                case DetectionSystem.GPU:
                    count = DetectImageGpu(pnt, imageData.Length, ref container);
                    break;
            }

            if (count == -1)
            {
                throw new NotImplementedException("C++ dll compiled incorrectly");
            }
        }
        catch (Exception exception)
        {
            return null;
        }
        finally
        {
            // Free the unmanaged memory.
            Marshal.FreeHGlobal(pnt);
        }

        return this.Convert(container);
    }

**Comment by JohnPekl** [comment]
Thanks for your effort.
This code works on Windows (**kernel32.dll**), despite of its name we can run the below code in x64. It is faster few milliseconds that is a reason you did not see any noticed performance improvement.
Since the mothod requires Intptr as an input, your code is optimized but if you have another method **public IEnumerable<YoloItem> Detect(_IntPtr_ imageData)**, **CopyMemory** would be better.
```
[DllImport("kernel32.dll", EntryPoint = "CopyMemory", SetLastError = false)]
private static extern void CopyMemory(IntPtr dest, IntPtr src, int count);
```

**Comment by tinohager** [comment]
In my test both variants needed about 27ms. So i think the difference is very small...
