### ISSUE TITLE
GPU and Cudnn not detected - very slow program

### ISSUE THREAD

**Issue by Flodkozza** [AlturosDestinations/Alturos.Yolo#43]
Why doesnt my gpu get detected? Gtx 1060.

**Comment by tinohager** [comment]
Have you follow this steps https://github.com/AlturosDestinations/Alturos.Yolo#gpu-requirements-optional
What is the value of wrapper.DetectionSystem  ?

**Comment by whatthefuckishappening** [comment]
Hey if i pass it throug a message box mine says wrapper was null , what can i do to fix this problem.
