### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by gunjeet40** [AlturosDestinations/Alturos.Yolo#49]
I am getting this error only for some images, for other it detects fine.

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Alturos.Yolo.YoloWrapper.Convert(BboxContainer container)
   at Alturos.Yolo.YoloWrapper.Detect(String filepath)

On debugging I found that it crashes inside the for each loop.

````
private IEnumerable<YoloItem> Convert(BboxContainer container)
        {
            var yoloItems = new List<YoloItem>();
            foreach (var item in container.candidates.Where(o => o.h > 0 || o.w > 0))
            {
                if (!this._objectType.TryGetValue((int)item.obj_id, out var objectType))
                {
                    objectType = "unknown key";
                }

                var yoloItem = new YoloItem
                {
                    X = (int)item.x,
                    Y = (int)item.y,
                    Height = (int)item.h,
                    Width = (int)item.w,
                    Confidence = item.prob,
                    Type = objectType
                };

                yoloItems.Add(yoloItem);
            }

            return yoloItems;
        }

````
Kindly help.

**Comment by tinohager** [comment]
If you are use the current version of Alturos.Yolo?

**Comment by gunjeet40** [comment]
@tinohager thank you that solved my problem.
