### ISSUE TITLE
Using GPU Acceleration

### ISSUE THREAD

**Issue by aakashpolra** [AlturosDestinations/Alturos.Yolo#5]
Hi,

Useful library but I have a question regarding GPU accelerated detection.
I have CUDA toolkit (9.2) installed and I have cuDNN downloaded as well. What do I need to do to reference cudnn64_7.dll in my project? When I add a reference in Visual Studio, it doesn't let me, so I'm guessing it's not that (presumably because it's not a valid .NET DLL).

Your help will be appreciated.

**Comment by tinohager** [comment]
copy cudnn64_7.dll in x64 folder with the other dlls

**Comment by aakashpolra** [comment]
Thanks! That did the job.
