### ISSUE TITLE
Index was out of range when i get item[0] = " Person...."

### ISSUE THREAD

**Issue by tt20496** [AlturosDestinations/Alturos.Yolo#50]
Hi everybody, i have a problem when i debug Alturos. How can i fix it? I'm newbie. Thanks so much
`This is my code:
private void ProcessFrame(object sender, EventArgs e)
        {
            imageBox1.Image = capture.QuerySmallFrame();
            var img = capture.QueryFrame();
            pictureBox1.Image = img.Bitmap;
            var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect();
            var yolo = new YoloWrapper(config);
            var memoryStream = new MemoryStream();
            pictureBox1.Image.Save(memoryStream, ImageFormat.Png);
            var _items = yolo.Detect(memoryStream.ToArray()).ToList();
           
            if (_items[0].Type == "tao") // Index was out of range. Must be non-negative and less than the size of the collection. 
            {
                serialPort1.Write("0");
            }
            serialPort1.Write("1");

            AddDetailsToPictureBox(pictureBox1, _items);
           
        }
`Error: Index was out of range. Must be non-negative and less than the size of the collection.

**Comment by tt20496** [comment]
[https://www.upsieutoc.com/image/x0KU6B](url)
picture my problem

**Comment by tinohager** [comment]
I think yolo has no results in the items object so you can`t access the index 0 check first if items has a length more as 0

**Comment by tt20496** [comment]
thanks for help but when program was detecting ( about 5s 6s or 30s ...), it had problem

**Comment by tinohager** [comment]
https://www.geeksforgeeks.org/how-to-find-the-length-of-an-array-in-c-sharp/
