### ISSUE TITLE
How to train to make Yolo differ face and person?

### ISSUE THREAD

**Issue by meomeo0110** [AlturosDestinations/Alturos.Yolo#52]
Hi,

The application need to detect the faces in the video, then censor them.
Alturos.Yolo is detecting face picture and person picture as 'person' label.
How can I make the Alturos.Yolo differ face and person?

Thanks,

**Comment by tinohager** [comment]
I don’t think it’s that easy.

But you can check this project.
https://github.com/abars/YoloKerasFaceDetection

**Comment by meomeo0110** [comment]
Thank you for information.
I will check.

**Comment by johnjake** [comment]
I am using haar cascade classifier to detect person faces using opencvsharp or other opencv wrapper the emgucv to detect faces. Now how do we train this faces and compare or recognize using Alturos as I understand this needs to be train the names and cfg I think.
