### ISSUE TITLE
Example of constructing byte[] array from image

### ISSUE THREAD

**Issue by asfarley** [AlturosDestinations/Alturos.Yolo#53]
Hi,

I'm hitting the "Invalid image data" exception; it seems that I am not constructing the byte[] array correctly which gets passed to Detector.Detect(). 

Do you have an example of building this array? In my case, I'm converting from an Emgu image (a wrapper on OpenCV images).

**Comment by tinohager** [comment]
Can you try this https://stackoverflow.com/questions/15406235/convert-emgucv-image-to-system-drawing-bitmap

**Comment by asfarley** [comment]
I have a small update: I was able to get the correct conversion using this method:

```
var converter = new ImageConverter();
var bytes = (byte[]) converter.ConvertTo(frame, typeof(byte[]));
```

I'm still having intermittent AccessViolationExceptions but I don't think it's related to the conversion here.
