### ISSUE TITLE
AccessViolationException after several calls to DetectImage

### ISSUE THREAD

**Issue by asfarley** [AlturosDestinations/Alturos.Yolo#54]
Hi,

I'm actually using AlexeyAB's repository, but I noticed a similar issue report here and thought I'd inquire. 

I am able to call DetectImage(IntPtr pArray, int nSize, ref BboxContainer container) several times before eventually getting an AccessViolationException. 

It's a bit unpredictable how soon this happens; sometimes I can call DetectImage only twice before hitting the exception, sometimes I can call it 5-10 times. 

Does this sound familiar at all?

**Comment by tinohager** [comment]
Maybe this thread can help you https://stackoverflow.com/questions/3469368/how-to-handle-accessviolationexception

**Comment by asfarley** [comment]
I've reviewed that thread; it seems to be more about catching/handling those exceptions. Setting the property [HandleProcessCorruptedStateExceptions] allows me to catch the AccessViolationException but it doesn't seem to add any information about why this is happening. 

I suspect this issue is related to the garbage-collector cleaning up something earlier than it should. 

I've tried adding GC.KeepAlive(pnt) to the end of Detect(byte[] imageData) but this doesn't fix the issue.

**Comment by tinohager** [comment]
In my enviorment it works without any AccessViolationException over 1000 DetectImage calls...

**Comment by asfarley** [comment]
Yes, I don't think this is a bug in your library; I think it's probably related to the garbage-collection in my own code, but I'm not certain how the byte[] array could be getting disposed. 

Anyway, thank you for the assistance; I will keep digging.

**Comment by asfarley** [comment]
This turned out to be my code Dispose'ing the Detector, then calling Detect on it. After fixing this, everything works correctly. Thanks for the assistance.

**Comment by metu** [comment]
Hi @tinohager @asfarley How did you manage to fix this exactly? I'm running multiple threads at once, each creating it's own instance of YoloWrapper and each disposing it's own instance when its done calling Detect().

From my experience it would seem the issues lies in yolo_cpp_dll_cpu.dll which doesn't appear to be threadsafe. But I don't seem to be getting strange results so it doesn't seem as if there's any race condition. It just seems as if the GC is disposing the yolo_cpp_dll_cpu dll.

@asfarley Were you running multiple threads at once?

Any help would be appreciated.

**Comment by metu** [comment]
Sorry. I was wondering if it was the right route to make YoloWrapper a singleton but wasn't sure how it would handle all the threads. Making it a singleton solved my issue. I basically looked at your Web API example.

**Comment by metu** [comment]
Mmmh I still get Access Violation errors every now and then. There's some weird garbage collection going on inside Detect() on cold starts.

**Comment by asfarley** [comment]
@metu Sounds like the correct approach with using a singleton. I didn't end up using this version of Yolo (I'm using AlexeyAB's Windows port) so I can't comment on GC specifics in this library.

**Comment by tinohager** [comment]
@metu try to add a lock on your method. https://stackoverflow.com/questions/6029804/how-does-lock-work-exactly
