### ISSUE TITLE
IsMicrosoftVisualCPlusPlus2017Available reports false even though MicrosoftVisualCPlusPlus is available

### ISSUE THREAD

**Issue by arronsmith** [AlturosDestinations/Alturos.Yolo#56]
Cause seems to be that there's a new Redist - `Microsoft Visual C++ 2015-2019 Redistributable (x64)`, whereas `IsMicrosoftCPlusPlus2017Available` is looking for `Microsoft Visual C++ 2017 Redistributable (x64)`.

```csharp
 if (displayName.StartsWith("Microsoft Visual C++ 2017 Redistributable (x64)", StringComparison.OrdinalIgnoreCase) || displayName.StartsWith("Microsoft Visual C++ 2015-2019 Redistributable (x64)", StringComparison.OrdinalIgnoreCase))
 {
        return true;
 }
```

fixes this, but it would probably be safe to simply check that the displayName starts with `Microsoft Visual C++` (or, I'm being optimistic here, is anything other than null or empty)...

Happy to raise a PR if that is useful.

(p.s. thanks for making and maintaining this it is awesome)

**Comment by tinohager** [comment]
Have you a download link for the new package?

**Comment by arronsmith** [comment]
I _think_ it might be [this](https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads) (or more specifically [the x64 version](https://aka.ms/vs/16/release/vc_redist.x64.exe) ), but that's a bit of a guess - I'm not near the relevant computer any more.
