### ISSUE TITLE
Crash with filename

### ISSUE THREAD

**Issue by CBergAccount** [AlturosDestinations/Alturos.Yolo#61]
It works great but one image it has a total crash which cant be catched with a try catch with the error:
External component has thrown an exception."}	System.Runtime.InteropServices.SEHException

it is on the row wrapper.Detect.
The file is a standard jpeg, although a small file.

Code:
 Using wrapper As New YoloWrapper(config)
            Dim items = wrapper.Detect(filename)
            For Each itm As YoloItem In items
                If itm.Confidence > 0.3 Then
                    objs.Add(New Classification(New System.Drawing.RectangleF(itm.X / imagewidth, itm.Y / imageheight, itm.Width / imagewidth, itm.Height / imageheight), itm.Type, itm.Confidence))
                End If

            Next
        End Using

Anyone can help out? I am happy that it cant solve the problem but less happy that it crashes my whole application....

**Comment by CBergAccount** [comment]
I tried the other way of loading the file into a byte array and use detect on that one and it worked without problem. So problem solved for me at least...

**Comment by tinohager** [comment]
Can close?

**Comment by CBergAccount** [comment]
@tinohager  Yes. Thanks
