### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by CBergAccount** [AlturosDestinations/Alturos.Yolo#63]
Sorry for the empty post :(

I am looking for knowledge how to distribute this to users. Is it as  simple ass including the project and the cudnn64_7.dll or do I need to do more at the users machine to get it to work under GPU?

All the Best
Christian

**Comment by tinohager** [comment]
I think you are need to check if a gpu available for fast processing. You are need a nvidia driver installed. c++ 2017 redistributable package must be installed. and after that the copy the dll. This is how it should work
