### ISSUE TITLE
Alturos.Yolo on Ubuntu via Mono

### ISSUE THREAD

**Issue by adamcaz** [AlturosDestinations/Alturos.Yolo#64]
Hello, i'm having some trouble getting Alturos to do any processing in Ubuntu ARM x64 under Mono. Would you have any suggestions or tips to get it to run properly? 

My project runs fine on Windows 10 and is doing object detection perfectly but I simply can't get it to do any processing under Ubuntu it simply reports no objects.

Any help would be really appreciated! Thank you. :)

**Comment by tinohager** [comment]
maybe you can try to download the source of the [yolo_cpp_dll_cpu.dll](https://github.com/AlexeyAB/darknet) and compile it for arm processor?
