### ISSUE TITLE
do you have the yolo3 classify example

### ISSUE THREAD

**Issue by mengpengfei** [AlturosDestinations/Alturos.Yolo#67]
do you have the yolo3 classify example

**Comment by tinohager** [comment]
What exactly do you mean by that?

**Comment by mengpengfei** [comment]
i would like to predict with the model of darknet19 network, it is only a classify network,
but i can not find a example that how to call the model to predict

**Comment by tinohager** [comment]
I think you must ask this question by https://github.com/AlexeyAB/darknet

This project is a wrapper project.
