### ISSUE TITLE
Yolo to train faces 

### ISSUE THREAD

**Issue by johnjake** [AlturosDestinations/Alturos.Yolo#69]
Hey I am relatively new to Yolo as I am mostly using opencv/Opencvsharp and Emgucv, I can detect faces, now I want to train this faces using yolo and recognize. How do we do it? I dont have python experience only C#. 

Best Regards 
John

**Comment by tinohager** [comment]
You can use this [project](https://github.com/AlturosDestinations/Alturos.ImageAnnotation) to annotate the images. After that you mast create a config and start the training process with the `darknet.exe`

**Comment by johnjake** [comment]
hey thank you very much for this I'm still on creating local aws
