### ISSUE TITLE
Question about loading the weights

### ISSUE THREAD

**Issue by leonylcabidog** [AlturosDestinations/Alturos.Yolo#70]
Hi good day,

I Just want to ask if its possible to load the weights on form load? not every-time it performs detection? Because i have a custom trained model, its a bit big. I was able to do it on Python, load the weights on first load, then just perform detection's onwards.

Thank you,
Leonyl

**Comment by johnjake** [comment]
I guess you could, this is similar to loading yml in opencv.

**Comment by leonylcabidog** [comment]
@johnjake Im afraid it may depend on how the Alturos.Yolo.dll was made. If they made a separate Public function for Initializing the yolo.

**Comment by tinohager** [comment]
I think you can do this in my example project i load the weights on load one time?

**Comment by leonylcabidog** [comment]
@tinohager are you referring to your TestConsole sample project?

**Comment by tinohager** [comment]
Check the `Alturos.Yolo.TestUI` project

**Comment by leonylcabidog** [comment]
@tinohager got it to work, thank you very much.
