### ISSUE TITLE
i need yolo tracking example

### ISSUE THREAD

**Issue by pokernet** [AlturosDestinations/Alturos.Yolo#71]
hi

can you please upload tracking exmaple how to use it ???

Thanks

**Comment by tinohager** [comment]
Check this class [YoloTracking.cs](/AlturosDestinations/Alturos.Yolo/blob/master/src/Alturos.Yolo/YoloTracking.cs)

**Comment by pokernet** [comment]
hi

i try t use it 
i replace 
 yoloWrapper.Detect(bmpBytes);
with
yoloTracking.Analyse(bmpBytes);
but i see its return only 1 item is it normal

i need to track multi items in video

how can i do this ?

**Comment by pokernet** [comment]
hi

i try t use it
i replace
yoloWrapper.Detect(bmpBytes);
with
yoloTracking.Analyse(bmpBytes);
but i see its return only 1 item is it normal

i need to track multi items in video

how can i do this ?

**Comment by tinohager** [comment]
we don't have a ready solution for your problem you have to build something for yourself
