### ISSUE TITLE
Why 2.4.4 update with no content?

### ISSUE THREAD

**Issue by xzessmedia** [AlturosDestinations/Alturos.Yolo#72]
I was very happy to read that a new version is out.
After checking the repository, the only changed file is the assembly where the version is increased.

If i am right, what was the reason for 2.4.4 if there is nothing changed except the assembly version??

https://github.com/AlturosDestinations/Alturos.Yolo/tree/master/src/Alturos.Yolo/Properties

**Comment by tinohager** [comment]
There are a some changes before, [commits](https://github.com/AlturosDestinations/Alturos.Yolo/commits/master) i have increase the version to push a new nuget package
