### ISSUE TITLE
Should include support for newer VC redist eg. 2019

### ISSUE THREAD

**Issue by Theoistic** [AlturosDestinations/Alturos.Yolo#73]
Should this be included. 

{ @"Installer\Dependencies\VC,redist.x64,amd64,14.23,bundle", "Microsoft Visual C++ 2015-2019 Redistributable (x64)" },

**Comment by tinohager** [comment]
Which Package you are use the current from microsoft is 14.22.27821

**Comment by SperoSophia** [comment]
i got 14.23 installed,

**Comment by tinohager** [comment]
Can you send me the download link?

**Comment by SperoSophia** [comment]
Got it via Visual Studio 2019 Preview ..

**Comment by SperoSophia** [comment]
Could this change also be pushed to the Alturos.YoloWithCuda101GpuSupport nuget package,
since i am running:
![image](https://user-images.githubusercontent.com/3510805/63936547-f69d9a00-ca57-11e9-8525-8b7481fbc094.png)

**Comment by SperoSophia** [comment]
additionally, how are you compiling the yolo dll dependency files?

**Comment by tinohager** [comment]
I compile the project from https://github.com/AlexeyAB/darknet
