### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Angshu1** [AlturosDestinations/Alturos.Yolo#74]
When Even i try to detect it throws an error :- System.IO.FileNotFoundException: 'Cannot found pre-trained model, check all config files available (.cfg, .weights, .names)'

My Code

            var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect(); //Error Throws here
            YoloWrapper yolo = new YoloWrapper(config);

**Comment by tinohager** [comment]
Please send the names of your files...

**Comment by Angshu1** [comment]
> Please send the names of your files...

Fixed By Installing New Version of Visual Studio and Yolo But i have a problem it ain't real time...
