### ISSUE TITLE
Not RealTime 

### ISSUE THREAD

**Issue by Angshu1** [AlturosDestinations/Alturos.Yolo#75]
The Wrapper isn't real time :< or am i doing something wrong? 
Delay:
The Delay is 25 Milliseconds
Average 20 Milliseconds

**Comment by tinohager** [comment]
How long does it take to evaluate an image?

**Comment by Angshu1** [comment]
> How long does it take to evaluate an image?

25-20-19 and the ui hangs as well but fixed with thread

**Comment by tinohager** [comment]
You are use CPU or GPU detection?

**Comment by Angshu1** [comment]
> You are use CPU or GPU detection?

Sorry I Don't Understand
My Code :- 

            //Process The Image
            Thread thread = new Thread(() =>
             {
                 var configurationDetector = new ConfigurationDetector();
                 var config = configurationDetector.Detect();
                 YoloWrapper yolo = new YoloWrapper(config);
                 MemoryStream memstream = new MemoryStream();
                 pictureBox1.Image.Save(memstream, ImageFormat.Png);
                 var output = yolo.Detect(memstream.ToArray()).ToList();
                 Action Do = () =>
                 {
                     Details(pictureBox1, output);
                 };
                 this.Invoke(Do);
             });
            thread.Start();
      //Add Details With Drawing
void Details(PictureBox picbox,List<YoloItem> output)
        {
            var font = new Font("Arial", 20, FontStyle.Bold);
            var brush = new SolidBrush(Color.Blue);

            var img = picbox.Image;
            var graphics = Graphics.FromImage(img);
            foreach (var obj in output)
            {
                var x = obj.X;
                var y = obj.Y;
                var width = obj.Width;
                var height = obj.Height;
                var rect = new Rectangle(x, y, width, height);
                var pen = new Pen(Color.Red,3);
                graphics.DrawRectangle(pen, rect);
                var point = new Point(x, y-10);
                graphics.DrawString(obj.Type, font, brush,point);
            }
            picbox.Image = img;
        }

**Comment by tinohager** [comment]
Only with a graphic device of nvidia you have real time detection
https://github.com/AlturosDestinations/Alturos.Yolo#gpu-requirements-optional

**Comment by Angshu1** [comment]
> Only with a graphic device of nvidia you have real time detection
> https://github.com/AlturosDestinations/Alturos.Yolo#gpu-requirements-optional

Okay I am Updating My Driver My Current Graphics Card is Gtx 710

**Comment by Angshu1** [comment]
> Only with a graphic device of nvidia you have real time detection
> https://github.com/AlturosDestinations/Alturos.Yolo#gpu-requirements-optional

uh oh , I've Installed the Latest Version of Graphics Card Driver but still it isn't Real time
