### ISSUE TITLE
Gpu mode not work

### ISSUE THREAD

**Issue by peterstark-code** [AlturosDestinations/Alturos.Yolo#76]
Hello, 

The CPU mode works perfectly but the GPU mode doesn't want. 

Can you help me ?  Thank so much in advance ! I'm on it since 3 days without any result.

Below the different screenshots : 
![image](https://user-images.githubusercontent.com/54742514/64290437-63d49200-cf66-11e9-8960-0ea1adfecd1e.png)

![image](https://user-images.githubusercontent.com/54742514/64290554-95e5f400-cf66-11e9-9a90-741cbc148b18.png)

![image](https://user-images.githubusercontent.com/54742514/64290879-3b00cc80-cf67-11e9-9436-b47fbef6d6c1.png)

**Comment by tinohager** [comment]
Have you some red missing dependencies on dependency walker?

**Comment by peterstark-code** [comment]
Thank you to take time to help. I got this : (question a put 3 screen shots in mail first message, can you read them ? )

Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

**Comment by tinohager** [comment]
Collapse the treeview and scroll down check if something have a red icon.

**Comment by jtorresc** [comment]
Hello, I had the same problem and what worked for me was to copy the files curand64_100.dll and cublas64_100.dll from the NVidia .....\bin folder to the x64 folder of the application. Be careful to download the correct cudnn64_7.dll for the NVidia version 10.0

**Comment by peterstark-code** [comment]
Hi Tino,

thanks for your very quick answer. So, I collapsed the tree and found nothing red. So I opened everything and I found 2 "red icon", but I don't know what does it mean. I also have a lot of yellow icon. 

![image](https://user-images.githubusercontent.com/54742514/64319771-7332fa00-cfbd-11e9-9070-6ec85a294ae0.png)

![image](https://user-images.githubusercontent.com/54742514/64319795-834ad980-cfbd-11e9-9fc6-3e9747c3b5d7.png)

**Comment by peterstark-code** [comment]
> 
> 
> Hello, I had the same problem and what worked for me was to copy the files curand64_100.dll and cublas64_100.dll from the NVidia .....\bin folder to the x64 folder of the application. Be careful to download the correct cudnn64_7.dll for the NVidia version 10.0

Hello !!

I installed the 10.1 version of the toolkit and the cuda. But the 10.1 has not the same name of files, like your curand64_100.dll became curand64_10.dll . Do you think it can be an issue ? 

![image](https://user-images.githubusercontent.com/54742514/64320708-67483780-cfbf-11e9-8008-b3ddca23aad8.png)

![image](https://user-images.githubusercontent.com/54742514/64320727-6e6f4580-cfbf-11e9-8582-956b5f0cc866.png)

**Comment by tinohager** [comment]
Can you use this tool again? https://github.com/lucasg/Dependencies/releases

![2019-09-05 10_22_14-Dependencies (x64)](https://user-images.githubusercontent.com/8215186/64324813-54396580-cfc7-11e9-9645-250146a21010.png)

**Comment by peterstark-code** [comment]
> 
> 
> Can you use this tool again? https://github.com/lucasg/Dependencies/releases
> 
> ![2019-09-05 10_22_14-Dependencies (x64)](https://user-images.githubusercontent.com/8215186/64324813-54396580-cfc7-11e9-9645-250146a21010.png)

hello !!

this is what I have : 
![image](https://user-images.githubusercontent.com/54742514/64335443-1e9e7780-cfdb-11e9-828d-2a5a0267fd2c.png)

I installed the 10.1 version of the toolkit and the cuda. But the 10.1 has not the same name of files, like your curand64_100.dll became curand64_10.dll . Do you think it can be an issue ?

![image](https://user-images.githubusercontent.com/54742514/64320708-67483780-cfbf-11e9-8008-b3ddca23aad8.png)

![image](https://user-images.githubusercontent.com/54742514/64335528-4ab9f880-cfdb-11e9-92f0-02e2550c3237.png)

**Comment by peterstark-code** [comment]
Okey it's running now !! I put in my folder x64 the lib curand64_10.dll and cublas64_10.dll from the 10.1 version and I change the name with _100, and it's running.
So, it seems you have to recompile yolo_cpp_dll_gpu.dll with the new name of nvdia lib.

Thank you so much for your time. I did this job when i had my own startup, I know how it takes time.

**Comment by jtorresc** [comment]
It is good to know that it worked for you too, take into account that renaming the DLL sometimes can involve unexpected compatibility issues, I also had installed Nvidia 10.1 and it did't work because of the names differences, so I uninstalled it and installed Nvidia 10.0 to avoid this possibility.
