### ISSUE TITLE
Error Detecting on a specific image of mine

### ISSUE THREAD

**Issue by titicruz** [AlturosDestinations/Alturos.Yolo#77]
I dont know why I'm having this error. I cant Catch the exception. Do you guys know what i can do?

**Comment by titicruz** [comment]
is there any limits for the size of the picture?

**Comment by tinohager** [comment]
What kind of image you are send? How big is your image?

**Comment by titicruz** [comment]
It is a .jpg and has 24,3 MB

**Comment by titicruz** [comment]
9088 x 3792 px

**Comment by tinohager** [comment]
Yolo shrink the image on background to 416x416 on the default yolo3 config. Send a large file to yolo have no benefit

**Comment by titicruz** [comment]
Oh Ok so the best thing to do is to shrink the image before I use the Detect method right?

**Comment by tinohager** [comment]
yes

**Comment by titicruz** [comment]
what do you think about changing the default on yolo3 config to a size that my camera takes pictures? like instead of 416x 416 maybe use 600x 300 or 900 x 450 because the average of my pictures are 6000x3000 px. Today at home I'm going to test this

**Comment by titicruz** [comment]
I'm building a database for all of my pictures to organize them. I'm using this to get all pictures that have person in it and then analyze the face with another method.

**Comment by tinohager** [comment]
Please read yourself into the topic https://github.com/AlexeyAB/darknet

**Comment by titicruz** [comment]
I Noticed that Using the Detect Method with a Byte[] as parameter it does not crash.
