### ISSUE TITLE
Best way to train custom models

### ISSUE THREAD

**Issue by VZcoding** [AlturosDestinations/Alturos.Yolo#78]
Hello, thank you so much for this amazing project. Finally i can run live recognition on wpf, and not using hard way via python. My question is what is the best way to train my custom model? There are labeling tools, thats fine, but you use next? Thanks

**Comment by tinohager** [comment]
We have develop this project for image annotation have you try it? https://github.com/AlturosDestinations/Alturos.ImageAnnotation

**Comment by VZcoding** [comment]
Yes thats just an annotation tool, its kind of hard to set it up, still struggling... But its just a tool for labeling right? or it will prepare the 3 needed output files as well?

**Comment by tinohager** [comment]
its also prepare the output files, we have add a powershell script for setup, if you have questions open an issue on this project
