### ISSUE TITLE
Problem with only GPU faster version

### ISSUE THREAD

**Issue by VZcoding** [AlturosDestinations/Alturos.Yolo#79]
Hi using simple version with CPU/GPU support i have no problems loading images internally. Now I really want to try to use cuda10.1 supported only GPU version. It instead of accepting img bytes array it ask for a string, why is that? How can I pass image after image using this parrameter?? Local images?? Could you please explain why this wrapper parameter type has been changed? Check the image bellow...

![Untitled](https://user-images.githubusercontent.com/35932738/65273145-2d337580-db29-11e9-9fc2-48517e360688.png)

**Comment by tinohager** [comment]
I think you have install this package? https://www.nuget.org/packages/Alturos.YoloWithCuda101GpuSupport/ this is not our package an other developer have push this package [DeltaEngine](https://www.nuget.org/profiles/DeltaEngine)

**Comment by VZcoding** [comment]
Yes thats the one installed, when I switch to original one the red squiggle goes away..
