### ISSUE TITLE
yolo9000 softmax last layer info

### ISSUE THREAD

**Issue by kinoc** [AlturosDestinations/Alturos.Yolo#8]
Thanks for the wonderful system! 
I have the package working with YOLO9000, and wanted to know if you could expose the scores assigned to _all_ the different possible labels of an object instead of just returning the argmax. I am interested in image retrieval and clustering, so having the additional info would help in with similarity indexing since you can use the entire scoring array as a long indexing vector for something like LSH.  Maybe return an optional Dictionary with type and confidence for each possible object type. Or a method that given the YoloItem would return the info.

**Comment by tinohager** [comment]
This project use in the backend the library of AlexeyAB/darknet. I add some methods to the project of AlexeyAB for c# communication. You can send a pull request to the project of AlexeyAB and after this i can integrate the new logic in this project. On this file we are need the new methods https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp
