### ISSUE TITLE
WindowsService throw Exception

### ISSUE THREAD

**Issue by kongfanming0809** [AlturosDestinations/Alturos.Yolo#81]
When I run by the WindowService,It throw an Exception:
System.NotSupportedException: Only 64-bit processes are supported,
my machine is 64 bit,Please tell me why,thinks?

**Comment by kongfanming0809** [comment]
Error Details=>错误信息:System.NotSupportedException: Only 64-bit processes are supported
   在 Alturos.Yolo.YoloWrapper.Initialize(String configurationFilename, String weightsFilename, String namesFilename, Int32 gpu, Boolean ignoreGpu, Boolean ignoreCPlusPlusDetection) 位置 D:\yoloV3\Alturos.Yolo-master\src\Alturos.Yolo\YoloWrapper.cs:行号 108
   在 Alturos.Yolo.YoloWrapper..ctor(String configurationFilename, String weightsFilename, String namesFilename, Int32 gpu, Boolean ignoreGpu) 位置 D:\yoloV3\Alturos.Yolo-master\src\Alturos.Yolo\YoloWrapper.cs:行号 88
   在 IntelligentRecognitionService.PerformanceAnalyze.Check(Boolean ignoreGpu) 位置 D:\yoloV3\Alturos.Yolo-master\src\IntelligentRecognitionService\PerformanceAnalyze.cs:行号 44

**Comment by tinohager** [comment]
![image](https://user-images.githubusercontent.com/8215186/68091142-519aa580-fe7c-11e9-8070-e2f2a758a4c1.png)

**Comment by kongfanming0809** [comment]
ok，thank you.

发自我的iPhone


------------------ Original ------------------
