### ISSUE TITLE
The exact required trained / pretrained files by Alturos.Yolo system for its operations.

### ISSUE THREAD

**Issue by Scared2Death** [AlturosDestinations/Alturos.Yolo#82]
Could someone please clarify what files Alturos.Yolo uses for the detection and its wrapper role? From what I notice it seems the YoloWrapper's constructor takes a .cfg, a .weights and a voc.names parameter. As so, does this mean that in case I train my own set of data I'm supposed to provide the training results in such formats, with nothing else being required?

Thanks in advance for any kind of clarification!

**Comment by tinohager** [comment]
Hi @Scared2Death 

Yes for your own model you need this 3 files.
 - .cfg = yolo config (shrink size of the image, )
 - .weigths = contains the trained object data
 - .names = contains the name of the objects, the weights file contains only a id

**Comment by Scared2Death** [comment]
@tinohager Thank you for your prompt answer!
