### ISSUE TITLE
Install failed on .NET 4.5

### ISSUE THREAD

**Issue by mridah** [AlturosDestinations/Alturos.Yolo#83]
When I try to install it on .NET 4.5, I get the following error:

> Install failed. Rolling back...
Package 'Alturos.Yolo.2.2.4' does not exist in project 'VisionTest'
Package 'Alturos.Yolo.2.2.4' does not exist in folder 'D:\softwares\VisionTest\packages'
Executing nuget actions took 12.15 sec
Install-Package : Could not install package 'Alturos.Yolo 2.2.4'. You are trying to install this package into a 
project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
 \+ Install-Package Alturos.Yolo -Version 2.2.4
 \+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
      + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackage 
   Command

**Comment by tinohager** [comment]
The current package require 4.6.1 of .net framework, you can compile it self if you are use .net 4.5
