### ISSUE TITLE
Error with cuda.

### ISSUE THREAD

**Issue by Mrproex** [AlturosDestinations/Alturos.Yolo#89]
Hi,

I have downloaded cuda following your instructions but i have an error :

![cudaError](https://user-images.githubusercontent.com/35890427/71324751-224eff00-24e3-11ea-950d-ff2029b9d3b6.png)

Is there a way to fix this ?

**Comment by tinohager** [comment]
Have you install the cuda 10.1 version?

**Comment by Mrproex** [comment]
Oww, I just realized your link lead to the version 10.2 mybad, thx for the help.

**Comment by Mrproex** [comment]
Link to the latest 10.1 :
https://developer.nvidia.com/cuda-10.1-download-archive-update2?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exenetwork

**Comment by tinohager** [comment]
i have add a extra notice -> It is important to use the mentioned version 10.1
