### ISSUE TITLE
DLL Exception Error

### ISSUE THREAD

**Issue by rossnoe** [AlturosDestinations/Alturos.Yolo#92]
Does Yolo work with Asp.net Core? I am using Yolo in a Asp.net Core 2.2 environment on Windows 10. I am seeing the following error:

DllNotFoundException: Unable to load DLL 'x64\yolo_cpp_dll_cpu.dll' or one of its dependencies: The specified module could not be found

Here is my MVC Controller action:

        public IActionResult TestYolo()
        {
            string imgPath = contentRootPath + "\\wwwroot\\images\\input.jpeg";
            string configFile = contentRootPath + "\\wwwroot\\data\\yolov2-tiny-voc.cfg";
            string weightFile = contentRootPath + "\\wwwroot\\data\\yolov2-tiny-voc.weights";
            string nameFile = contentRootPath + "\\wwwroot\\data\\voc.names";

            using (var yoloWrapper = new YoloWrapper(configFile, weightFile, nameFile))
            {
                var items = yoloWrapper.Detect(imgPath);
                //items[0].Type -> "Person, Car, ..."
                //items[0].Confidence -> 0.0 (low) -> 1.0 (high)
                //items[0].X -> bounding box
                //items[0].Y -> bounding box
                //items[0].Width -> bounding box
                //items[0].Height -> bounding box
            }

            return View();
        }

**Comment by tinohager** [comment]
please try the alpha package `Install-Package Alturos.Yolo -Version 3.0.2-alpha`

**Comment by rossnoe** [comment]
After I installed version 3.0.3-alpha there is now a different issue - the debugging process crashes.  The browser window closes and debugging stops.

**Comment by tinohager** [comment]
Have you some information in the event log? what the output if you start the website with `dotnet run`

**Comment by rossnoe** [comment]
You may close this issue. It is not important for me to get this to work. I was simply experimenting and comparing it to Yolo.

**Comment by rossnoe** [comment]
You may close this issue. It is not important for me to get this to work. I was simply experimenting and comparing it to DLib.
