### ISSUE TITLE
Where do I should put my custom model: .weights, .cfg, .name?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [AlturosDestinations/Alturos.Yolo#93]
I have custom trained models on Yolo Tiny v3, including .cfg, .name. But I don't know how to use this custom model for my own project. Pls, guide me on how to do that. Thank you so much!

**Comment by tinohager** [comment]
Use this documentation https://github.com/AlturosDestinations/Alturos.Yolo#detect-the-type-and-the-position-of-an-image-manual-configuration
