### ISSUE TITLE
BFLOPS count very low on run

### ISSUE THREAD

**Issue by whatthefuckishappening** [AlturosDestinations/Alturos.Yolo#96]
When i run my code and stream the video on my webcam i have very low fps even though I have met the GPU requirements for it to run with the GPU

**Comment by tinohager** [comment]
Maybe your code not use the gpu and run on the cpu? The code check if gpu possible automatic...

**Comment by Mrproex** [comment]
> When i run my code and stream the video on my webcam i have very low fps even though I have met the GPU requirements for it to run with the GPU

What is your GPU ? I do have a rtx2070 but still low on fps.

**Comment by whatthefuckishappening** [comment]
I have it on GPU, the problem is the frame rate's like 1 
 
![image](https://user-images.githubusercontent.com/32835298/73384730-c9a32b00-4306-11ea-91ce-36b72ced8de5.png)

**Comment by tinohager** [comment]
You are create the wrapper for every image again this need time. You must config the wrapper on start of your application and call then only yolo.Detect()

**Comment by whatthefuckishappening** [comment]
![image](https://user-images.githubusercontent.com/32835298/73391072-3ff95a80-4312-11ea-8c97-acb8aa420d15.png)
Thanks for getting back on a short notice , so i tried it and the problem now is that the bounding boxes don't spawn 
what do you think might be the problem now

**Comment by tinohager** [comment]
Sorry but for general programming questions please use stackoverlow.

**Comment by whatthefuckishappening** [comment]
It's okay , thanks for the tip Bless you
