### ISSUE TITLE
Dependency to api-ms-win-core-wow64-l1-1-0

### ISSUE THREAD

**Issue by tarnow74** [AlturosDestinations/Alturos.Yolo#98]
When running DependenciesGui.exe on yolo_cpp_dll_gpu.dll i get an error on missing api-ms-win-core-wow64-l1-1-0.dll from System32\WS2_32.dll

On my win 10 the dll is located under system32\downlevel but it doesn't seem to match the required version

Any idea on how to fix this issue

**Comment by tinohager** [comment]
No sorry, on my pc it works without any issue

**Comment by tarnow74** [comment]
I reinstalled windows 10, Visual Studio 2091 and cuda and I finally have everything working and was also able to compile darnet.exe for training
