### ISSUE TITLE
How can I detect by camera or video?

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [AlturosDestinations/Alturos.Yolo#99]
So sorry for this question but actually I don't know how to connect to camera or video for object detection. Could you tell me how to do that from this code tutorial?

var configurationDetector = new ConfigurationDetector();
var config = configurationDetector.Detect();
using (var yoloWrapper = new YoloWrapper(config))
{
	var items = yoloWrapper.Detect(@"image.jpg");
	//items[0].Type -> "Person, Car, ..."
	//items[0].Confidence -> 0.0 (low) -> 1.0 (high)
	//items[0].X -> bounding box
	//items[0].Y -> bounding box
	//items[0].Width -> bounding box
	//items[0].Height -> bounding box
}
Thank you so much!

**Comment by tinohager** [comment]
What camera do you use?

**Comment by nguyenanhtuan1008** [comment]
Sorry for late reply. I'm using a USB camera and an ethernet camera also. But I don't know how to use a camera inside the code. If I use python I will use cv2.Cameracapture(0) but I'm newb C# so I don't know how to use this.

**Comment by nguyenanhtuan1008** [comment]
Ok so now I already run it in camera by emgucv but my code load model every single frame. How do I load model only one time for all frame? Can you read my code below then pls tell me how can I do? Thank you!

using Alturos.Yolo;
using Alturos.Yolo.Model;
using Emgu.CV;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Yolo_camera_app
{
    public partial class Form1 : Form
    {
        VideoCapture capture;
        public Form1()
        {
            InitializeComponent();
            Run();
        }

        

        private void Run()
        {
            try
            {
                capture = new VideoCapture();
            }
            catch (Exception Ex)
            {
                MessageBox.Show(Ex.Message);
                return;
            }
            Application.Idle += ProcessFrame;
        }

        private void ProcessFrame(object sender, EventArgs e)
        {
            var img = capture.QuerySmallFrame();
            pictureBox1.Image = img.ToBitmap();
            var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect();

            using (var yoloWrapper = new YoloWrapper(config))
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    pictureBox1.Image.Save(ms, ImageFormat.Png);
                    var _items = yoloWrapper.Detect(ms.ToArray()).ToList();
                    AddDetailsToPictureBox(pictureBox1, _items);
                    //yoloItemBindingSource.DataSource = items;
                    //arr = items.ToArray();
                }
            }
            //Detect();
        }
        
        //private void detect()
        //{
        //    var configurationdetector = new configurationdetector();
        //    var config = configurationdetector.detect();
        //    var yolo = new yolowrapper(config);
        //    var memorystream = new memorystream();
        //    picturebox1.image.save(memorystream, imageformat.png);
        //    var _items = yolo.detect(memorystream.toarray()).tolist();
        //    adddetailstopicturebox(picturebox1, _items);
        //}

        private void AddDetailsToPictureBox(PictureBox pictureBox1, List<YoloItem> items)
        {
            var img = pictureBox1.Image;
            var font = new Font("Arial", 18, FontStyle.Bold);
            var brush = new SolidBrush(Color.Red);
            var graphics = Graphics.FromImage(img);
            foreach (var item in items)
            {
                var x = item.X;
                var y = item.Y;
                var width = item.Width;
                var height = item.Height;
                var tuan = item.Type;
                var rect = new Rectangle(x, y, width, height);
                var pen = new Pen(Color.LightGreen, 6);
                var point = new Point(x, y);
                graphics.DrawRectangle(pen, rect);
                graphics.DrawString(item.Type, font, brush, point);
            }
            pictureBox1.Image = img;
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }
    }
}

**Comment by tinohager** [comment]
Try this

```
using Alturos.Yolo;
using Alturos.Yolo.Model;
using Emgu.CV;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Yolo_camera_app
{
    public partial class Form1 : Form
    {
        YoloWrapper yoloWrapper;
        VideoCapture capture;

        public Form1()
        {
            InitializeComponent();
            Run();
            var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect();
            yoloWrapper = new YoloWrapper(config);
        }

        private void Run()
        {
            try
            {
                capture = new VideoCapture();
            }
            catch (Exception Ex)
            {
                MessageBox.Show(Ex.Message);
                return;
            }
            Application.Idle += ProcessFrame;
        }

        private void ProcessFrame(object sender, EventArgs e)
        {
            var img = capture.QuerySmallFrame();
            pictureBox1.Image = img.ToBitmap();
            var configurationDetector = new ConfigurationDetector();
            var config = configurationDetector.Detect();

            using (MemoryStream ms = new MemoryStream())
            {
                pictureBox1.Image.Save(ms, ImageFormat.Png);
                var _items = yoloWrapper.Detect(ms.ToArray()).ToList();
                AddDetailsToPictureBox(pictureBox1, _items);
                //yoloItemBindingSource.DataSource = items;
                //arr = items.ToArray();
            }
            //Detect();
        }
        
        //private void detect()
        //{
        //    var configurationdetector = new configurationdetector();
        //    var config = configurationdetector.detect();
        //    var yolo = new yolowrapper(config);
        //    var memorystream = new memorystream();
        //    picturebox1.image.save(memorystream, imageformat.png);
        //    var _items = yolo.detect(memorystream.toarray()).tolist();
        //    adddetailstopicturebox(picturebox1, _items);
        //}

        private void AddDetailsToPictureBox(PictureBox pictureBox1, List<YoloItem> items)
        {
            var img = pictureBox1.Image;
            var font = new Font("Arial", 18, FontStyle.Bold);
            var brush = new SolidBrush(Color.Red);
            var graphics = Graphics.FromImage(img);
            foreach (var item in items)
            {
                var x = item.X;
                var y = item.Y;
                var width = item.Width;
                var height = item.Height;
                var tuan = item.Type;
                var rect = new Rectangle(x, y, width, height);
                var pen = new Pen(Color.LightGreen, 6);
                var point = new Point(x, y);
                graphics.DrawRectangle(pen, rect);
                graphics.DrawString(item.Type, font, brush, point);
            }
            pictureBox1.Image = img;
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }
    }
}
```

**Comment by nguyenanhtuan1008** [comment]
So sorry for the late reply. I will try it then let you know soon. Thank you!

**Comment by yr-lee7** [comment]
Hello, I want to detect through the camera, so I ran the code.
However, I get the following error in the "memoryStream" part.

**Compiler Error CS1503
Cannot convert from argument 'byte[]' to 'string'.**

Can you tell me how to solve it?
Thank you!
